<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="pt-BR" xml:lang="pt-BR"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Prof.&nbsp;Me. Maxwell Anderson Ielpo do Amaral">

<title>Aula 07 — Interferência e Algoritmo de Deutsch-Jozsa – Fundamentos de Computação Quântica</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-dark-53dc85963c67a221f6f2030af840abbe.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-03eae88be18a08608b408ecf67964427.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="dark">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "Nenhum resultado",
    "search-matching-documents-text": "documentos correspondentes",
    "search-copy-link-title": "Copiar link para a busca",
    "search-hide-matches-text": "Esconder correspondências adicionais",
    "search-more-match-text": "mais correspondência neste documento",
    "search-more-matches-text": "mais correspondências neste documento",
    "search-clear-button-title": "Limpar",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancelar",
    "search-submit-button-title": "Enviar",
    "search-label": "Procurar"
  }
}</script>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/monaco-editor@0.46.0/min/vs/editor/editor.main.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA==" crossorigin="anonymous" referrerpolicy="no-referrer">
  
<style type="text/css">
.monaco-editor pre {
  background-color: unset !important;
}

.qpyodide-editor-toolbar {
  width: 100%;
  display: flex;
  justify-content: space-between;
  box-sizing: border-box;
}

.qpyodide-editor-toolbar-left-buttons, .qpyodide-editor-toolbar-right-buttons {
  display: flex;
}

.qpyodide-non-interactive-loading-container.qpyodide-cell-needs-evaluation, .qpyodide-non-interactive-loading-container.qpyodide-cell-evaluated {
  justify-content: center;
  display: flex;
  background-color: rgba(250, 250, 250, 0.65);
  border: 1px solid rgba(233, 236, 239, 0.65);
  border-radius: 0.5rem;
  margin-top: 15px;
  margin-bottom: 15px;
}

.qpyodide-r-project-logo {
  color: #2767B0; /* R Project's blue color */
}

.qpyodide-icon-status-spinner {
  color: #7894c4;
}

.qpyodide-icon-run-code {
  color: #0d9c29
}

.qpyodide-output-code-stdout {
  color: #111;
}

.qpyodide-output-code-stderr {
  color: #db4133;
}

.qpyodide-editor {
  border: 1px solid #EEEEEE;
}

.qpyodide-editor-toolbar {
  background-color: #EEEEEE;
  padding: 0.2rem 0.5rem;
}

.qpyodide-button {
  background-color: #EEEEEE;
  display: inline-block;
  font-weight: 400;
  line-height: 1;
  text-decoration: none;
  text-align: center;
  color: #000;
  border-color: #dee2e6;
  border: 1px solid rgba(0,0,0,0);
  padding: 0.375rem 0.75rem;
  font-size: .9rem;
  border-radius: 0.25rem;
  transition: color .15s ease-in-out,background-color .15s ease-in-out,border-color .15s ease-in-out,box-shadow .15s ease-in-out;
}

.qpyodide-button:hover {
  color: #000;
  background-color: #d9dce0;
  border-color: #c8ccd0;
}

.qpyodide-button:disabled,.qpyodide-button.disabled,fieldset:disabled .qpyodide-button {
  pointer-events: none;
  opacity: .65
}

.qpyodide-button-reset {
  color: #696969; /*#4682b4;*/
}

.qpyodide-button-copy {
  color: #696969;
}


/* Custom styling for RevealJS Presentations*/

/* Reset the style of the interactive area */
.reveal div.qpyodide-interactive-area {
  display: block;
  box-shadow: none;
  max-width: 100%;
  max-height: 100%;
  margin: 0;
  padding: 0;
} 

/* Provide space to entries */
.reveal div.qpyodide-output-code-area pre div {
  margin: 1px 2px 1px 10px;
}

/* Collapse the inside code tags to avoid extra space between line outputs */
.reveal pre div code.qpyodide-output-code-stdout, .reveal pre div code.qpyodide-output-code-stderr {
  padding: 0;
  display: contents;
}

.reveal pre div code.qpyodide-output-code-stdout {
  color: #111;
}

.reveal pre div code.qpyodide-output-code-stderr {
  color: #db4133;
}


/* Create a border around console and output (does not effect graphs) */
.reveal div.qpyodide-console-area {
  border: 1px solid #EEEEEE;
  box-shadow: 2px 2px 10px #EEEEEE;
}

/* Cap output height and allow text to scroll */
/* TODO: Is there a better way to fit contents/max it parallel to the monaco editor size? */
.reveal div.qpyodide-output-code-area pre {
  max-height: 400px;
  overflow: scroll;
}
</style>
<script type="module">
// Document level settings ----

// Determine if we need to install python packages
globalThis.qpyodideInstallPythonPackagesList = [''];

// Check to see if we have an empty array, if we do set to skip the installation.
globalThis.qpyodideSetupPythonPackages = !(qpyodideInstallPythonPackagesList.indexOf("") !== -1);

// Display a startup message?
globalThis.qpyodideShowStartupMessage = true;

// Describe the webR settings that should be used
globalThis.qpyodideCustomizedPyodideOptions = {
  "indexURL": "https://cdn.jsdelivr.net/pyodide/v0.27.2/full/",
  "env": {
    "HOME": "/home/pyodide",
  }, 
  stdout: (text) => {qpyodideAddToOutputArray(text, "out");},
  stderr: (text) => {qpyodideAddToOutputArray(text, "error");}
}

// Store cell data
globalThis.qpyodideCellDetails = [];


</script>
<script type="module">
// Declare startupMessageqpyodide globally
globalThis.qpyodideStartupMessage = document.createElement("p");

// Function to set the button text
globalThis.qpyodideSetInteractiveButtonState = function(buttonText, enableCodeButton = true) {
  document.querySelectorAll(".qpyodide-button-run").forEach((btn) => {
    btn.innerHTML = buttonText;
    btn.disabled = !enableCodeButton;
  });
}

// Function to update the status message in non-interactive cells
globalThis.qpyodideUpdateStatusMessage = function(message) {
  document.querySelectorAll(".qpyodide-status-text.qpyodide-cell-needs-evaluation").forEach((elem) => {
    elem.innerText = message;
  });
}

// Function to update the status message
globalThis.qpyodideUpdateStatusHeader = function(message) {

  if (!qpyodideShowStartupMessage) return;

  qpyodideStartupMessage.innerHTML = message;
}

// Status header update with customized spinner message
globalThis.qpyodideUpdateStatusHeaderSpinner = function(message) {

  qpyodideUpdateStatusHeader(`
    <i class="fa-solid fa-spinner fa-spin qpyodide-icon-status-spinner"></i>
    <span>${message}</span>
  `);
}


// Function that attaches the document status message
function qpyodideDisplayStartupMessage(showStartupMessage) {
  if (!showStartupMessage) {
    return;
  }

  // Get references to header elements
  const headerHTML = document.getElementById("title-block-header");
  const headerRevealJS = document.getElementById("title-slide");

  // Create the outermost div element for metadata
  const quartoTitleMeta = document.createElement("div");
  quartoTitleMeta.classList.add("quarto-title-meta");

  // Create the first inner div element
  const firstInnerDiv = document.createElement("div");
  firstInnerDiv.setAttribute("id", "qpyodide-status-message-area");

  // Create the second inner div element for "Pyodide Status" heading and contents
  const secondInnerDiv = document.createElement("div");
  secondInnerDiv.setAttribute("id", "qpyodide-status-message-title");
  secondInnerDiv.classList.add("quarto-title-meta-heading");
  secondInnerDiv.innerText = "Pyodide Status";

  // Create another inner div for contents
  const secondInnerDivContents = document.createElement("div");
  secondInnerDivContents.setAttribute("id", "qpyodide-status-message-body");
  secondInnerDivContents.classList.add("quarto-title-meta-contents");

  // Describe the Pyodide state
  qpyodideStartupMessage.innerText = "🟡 Loading...";
  qpyodideStartupMessage.setAttribute("id", "qpyodide-status-message-text");
  // Add `aria-live` to auto-announce the startup status to screen readers
  qpyodideStartupMessage.setAttribute("aria-live", "assertive");

  // Append the startup message to the contents
  secondInnerDivContents.appendChild(qpyodideStartupMessage);

  // Combine the inner divs and contents
  firstInnerDiv.appendChild(secondInnerDiv);
  firstInnerDiv.appendChild(secondInnerDivContents);
  quartoTitleMeta.appendChild(firstInnerDiv);

  // Determine where to insert the quartoTitleMeta element
  if (headerHTML || headerRevealJS) {
    // Append to the existing "title-block-header" element or "title-slide" div
    (headerHTML || headerRevealJS).appendChild(quartoTitleMeta);
  } else {
    // If neither headerHTML nor headerRevealJS is found, insert after "Pyodide-monaco-editor-init" script
    const monacoScript = document.getElementById("qpyodide-monaco-editor-init");
    const header = document.createElement("header");
    header.setAttribute("id", "title-block-header");
    header.appendChild(quartoTitleMeta);
    monacoScript.after(header);
  }
}

qpyodideDisplayStartupMessage(qpyodideShowStartupMessage);
</script>
<script type="module">
// Create a logging setup
globalThis.qpyodideMessageArray = []

// Add messages to array
globalThis.qpyodideAddToOutputArray = function(message, type) {
  qpyodideMessageArray.push({ message, type });
}

// Function to reset the output array
globalThis.qpyodideResetOutputArray = function() {
  qpyodideMessageArray = [];
}

globalThis.qpyodideRetrieveOutput = function() {
  return qpyodideMessageArray.map(entry => entry.message).join('\n');
}

// Start a timer
const initializePyodideTimerStart = performance.now();

// Encase with a dynamic import statement
globalThis.qpyodideInstance = await import(
  qpyodideCustomizedPyodideOptions.indexURL + "pyodide.mjs").then(
   async({ loadPyodide }) => {

    console.log("Start loading Pyodide");
    
    // Populate Pyodide options with defaults or new values based on `pyodide`` meta
    let mainPyodide = await loadPyodide(
      qpyodideCustomizedPyodideOptions
    );
    
    // Setup a namespace for global scoping
    // await loadedPyodide.runPythonAsync("globalScope = {}"); 
    
    // Update status to reflect the next stage of the procedure
    qpyodideUpdateStatusHeaderSpinner("Initializing Python Packages");

    // Load the `micropip` package to allow installation of packages.
    await mainPyodide.loadPackage("micropip");
    await mainPyodide.runPythonAsync(`import micropip`);

    // Load the `pyodide_http` package to shim uses of `requests` and `urllib3`.
    // This allows for `pd.read_csv(url)` to work flawlessly.
    // Details: https://github.com/coatless-quarto/pyodide/issues/9
    await mainPyodide.loadPackage("pyodide_http");
    await mainPyodide.runPythonAsync(`
    import pyodide_http
    pyodide_http.patch_all()  # Patch all libraries
    `);

    // Load the `matplotlib` package with necessary environment hook
    await mainPyodide.loadPackage("matplotlib");

    // Set the backend for matplotlib to be interactive.
    await mainPyodide.runPythonAsync(`
    import matplotlib
    matplotlib.use("module://matplotlib_pyodide.html5_canvas_backend")
    from matplotlib import pyplot as plt
    `);

    // Unlock interactive buttons
    qpyodideSetInteractiveButtonState(
      `<i class="fa-solid fa-play qpyodide-icon-run-code"></i> <span>Run Code</span>`, 
      true
    );

    // Set document status to viable
    qpyodideUpdateStatusHeader(
      "🟢 Ready!"
    );

    // Assign Pyodide into the global environment
    globalThis.mainPyodide = mainPyodide;

    console.log("Completed loading Pyodide");
    return mainPyodide;
  }
);

// Stop timer
const initializePyodideTimerEnd = performance.now();

// Create a function to retrieve the promise object.
globalThis._qpyodideGetInstance = function() {
    return qpyodideInstance;
}

</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@4/tex-chtml.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../../assets/css/styles.css">
</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Fundamentos de Computação Quântica</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Procurar"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Alternar de navegação" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html"> 
<span class="menu-text">Início</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../content/index.html"> 
<span class="menu-text">Aulas &amp; Materiais</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../about.html"> 
<span class="menu-text">Sobre</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../content/apostila.pdf"> 
<span class="menu-text">📄 Baixar PDF Completo</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Nesta página</h2>
   
  <ul>
  <li><a href="#aula-07-interferência-quântica-e-algoritmo-de-deutsch-jozsa" id="toc-aula-07-interferência-quântica-e-algoritmo-de-deutsch-jozsa" class="nav-link active" data-scroll-target="#aula-07-interferência-quântica-e-algoritmo-de-deutsch-jozsa">Aula 07 — Interferência Quântica e Algoritmo de Deutsch-Jozsa</a></li>
  <li><a href="#interferência-quântica-e-algoritmos" id="toc-interferência-quântica-e-algoritmos" class="nav-link" data-scroll-target="#interferência-quântica-e-algoritmos">Interferência Quântica e Algoritmos</a>
  <ul class="collapse">
  <li><a href="#visão-geral" id="toc-visão-geral" class="nav-link" data-scroll-target="#visão-geral">📖 Visão Geral</a>
  <ul class="collapse">
  <li><a href="#o-que-você-vai-aprender" id="toc-o-que-você-vai-aprender" class="nav-link" data-scroll-target="#o-que-você-vai-aprender">🎯 O Que Você Vai Aprender</a></li>
  <li><a href="#pré-requisitos" id="toc-pré-requisitos" class="nav-link" data-scroll-target="#pré-requisitos">📚 Pré-requisitos</a></li>
  <li><a href="#nível-de-dificuldade" id="toc-nível-de-dificuldade" class="nav-link" data-scroll-target="#nível-de-dificuldade">🎓 Nível de Dificuldade</a></li>
  <li><a href="#por-que-este-conteúdo-é-importante" id="toc-por-que-este-conteúdo-é-importante" class="nav-link" data-scroll-target="#por-que-este-conteúdo-é-importante">💡 Por Que Este Conteúdo é Importante?</a></li>
  <li><a href="#estrutura-do-notebook" id="toc-estrutura-do-notebook" class="nav-link" data-scroll-target="#estrutura-do-notebook">🗺️ Estrutura do Notebook</a></li>
  </ul></li>
  <li><a href="#phase-kickback-e-o-algoritmo-de-deutsch-jozsa" id="toc-phase-kickback-e-o-algoritmo-de-deutsch-jozsa" class="nav-link" data-scroll-target="#phase-kickback-e-o-algoritmo-de-deutsch-jozsa">Phase Kickback e o Algoritmo de Deutsch-Jozsa</a>
  <ul class="collapse">
  <li><a href="#o-conceito-phase-kickback-o-recuo-da-arma" id="toc-o-conceito-phase-kickback-o-recuo-da-arma" class="nav-link" data-scroll-target="#o-conceito-phase-kickback-o-recuo-da-arma">1. O Conceito: Phase Kickback (O Recuo da Arma)</a></li>
  <li><a href="#o-estado-inicial" id="toc-o-estado-inicial" class="nav-link" data-scroll-target="#o-estado-inicial">O Estado Inicial</a></li>
  <li><a href="#visualização-estado-inicial-preparado" id="toc-visualização-estado-inicial-preparado" class="nav-link" data-scroll-target="#visualização-estado-inicial-preparado">Visualização: Estado Inicial Preparado</a></li>
  </ul></li>
  <li><a href="#q-sphere" id="toc-q-sphere" class="nav-link" data-scroll-target="#q-sphere">Q-Sphere</a>
  <ul class="collapse">
  <li><a href="#o-algoritmo-de-deutsch-jozsa" id="toc-o-algoritmo-de-deutsch-jozsa" class="nav-link" data-scroll-target="#o-algoritmo-de-deutsch-jozsa">2. O Algoritmo de Deutsch-Jozsa</a></li>
  </ul></li>
  <li><a href="#versão-quântica-do-problema" id="toc-versão-quântica-do-problema" class="nav-link" data-scroll-target="#versão-quântica-do-problema">🚀 Versão Quântica do Problema</a>
  <ul class="collapse">
  <li><a href="#comparação-clássico-vs-quântico" id="toc-comparação-clássico-vs-quântico" class="nav-link" data-scroll-target="#comparação-clássico-vs-quântico">📊 Comparação: Clássico vs Quântico</a></li>
  <li><a href="#estratégia-pedagógica" id="toc-estratégia-pedagógica" class="nav-link" data-scroll-target="#estratégia-pedagógica">🎯 Estratégia Pedagógica</a></li>
  </ul></li>
  <li><a href="#entendendo-o-resultado-em-profundidade" id="toc-entendendo-o-resultado-em-profundidade" class="nav-link" data-scroll-target="#entendendo-o-resultado-em-profundidade">🔍 Entendendo o Resultado em Profundidade</a>
  <ul class="collapse">
  <li><a href="#interpretação-dos-resultados" id="toc-interpretação-dos-resultados" class="nav-link" data-scroll-target="#interpretação-dos-resultados">📊 Interpretação dos Resultados</a></li>
  <li><a href="#por-que-isso-funciona" id="toc-por-que-isso-funciona" class="nav-link" data-scroll-target="#por-que-isso-funciona">🔬 Por Que Isso Funciona?</a></li>
  <li><a href="#demonstração-matemática-simplificada" id="toc-demonstração-matemática-simplificada" class="nav-link" data-scroll-target="#demonstração-matemática-simplificada">🧮 Demonstração Matemática Simplificada</a></li>
  <li><a href="#comparação-final-clássico-vs-quântico" id="toc-comparação-final-clássico-vs-quântico" class="nav-link" data-scroll-target="#comparação-final-clássico-vs-quântico">💻 Comparação Final: Clássico vs Quântico</a></li>
  <li><a href="#o-insight-principal" id="toc-o-insight-principal" class="nav-link" data-scroll-target="#o-insight-principal">🎯 O Insight Principal</a></li>
  <li><a href="#limitações-importantes" id="toc-limitações-importantes" class="nav-link" data-scroll-target="#limitações-importantes">⚠️ Limitações Importantes</a></li>
  <li><a href="#experimento-teste-você-mesmo" id="toc-experimento-teste-você-mesmo" class="nav-link" data-scroll-target="#experimento-teste-você-mesmo">🔬 Experimento: Teste Você Mesmo!</a></li>
  <li><a href="#desafio-adicional" id="toc-desafio-adicional" class="nav-link" data-scroll-target="#desafio-adicional">🧪 Desafio Adicional</a></li>
  </ul></li>
  <li><a href="#resumo-e-conceitos-aprendidos" id="toc-resumo-e-conceitos-aprendidos" class="nav-link" data-scroll-target="#resumo-e-conceitos-aprendidos">📚 Resumo e Conceitos Aprendidos</a>
  <ul class="collapse">
  <li><a href="#conceitos-fundamentais" id="toc-conceitos-fundamentais" class="nav-link" data-scroll-target="#conceitos-fundamentais">🎯 Conceitos Fundamentais</a></li>
  <li><a href="#técnicas-aprendidas" id="toc-técnicas-aprendidas" class="nav-link" data-scroll-target="#técnicas-aprendidas">🔬 Técnicas Aprendidas</a></li>
  <li><a href="#por-que-isso-é-importante" id="toc-por-que-isso-é-importante" class="nav-link" data-scroll-target="#por-que-isso-é-importante">🚀 Por Que Isso É Importante?</a></li>
  <li><a href="#insights-principais" id="toc-insights-principais" class="nav-link" data-scroll-target="#insights-principais">💡 Insights Principais</a></li>
  <li><a href="#próximos-passos" id="toc-próximos-passos" class="nav-link" data-scroll-target="#próximos-passos">🎓 Próximos Passos</a></li>
  <li><a href="#reflexão-final" id="toc-reflexão-final" class="nav-link" data-scroll-target="#reflexão-final">✨ Reflexão Final</a></li>
  <li><a href="#referências-adicionais" id="toc-referências-adicionais" class="nav-link" data-scroll-target="#referências-adicionais">📖 Referências Adicionais</a></li>
  </ul></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">
<script src="https://cdn.jsdelivr.net/npm/monaco-editor@0.46.0/min/vs/loader.js"></script>
<script type="module" id="qpyodide-monaco-editor-init">

  // Configure the Monaco Editor's loader
  require.config({
    paths: {
      'vs': 'https://cdn.jsdelivr.net/npm/monaco-editor@0.46.0/min/vs'
    }
  });
</script>

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<div class="quarto-title-block"><div><h1 class="title">Aula 07 — Interferência e Algoritmo de Deutsch-Jozsa</h1><button type="button" class="btn code-tools-button" id="quarto-code-tools-source"><i class="bi"></i> Código</button></div></div>
<p class="subtitle lead">Fundamentos de Computação Quântica — Curso de Extensão</p>
</div>


<div class="quarto-title-meta-author">
  <div class="quarto-title-meta-heading">Autor</div>
  <div class="quarto-title-meta-heading">Afiliação</div>
  
    <div class="quarto-title-meta-contents">
    <p class="author">Prof.&nbsp;Me. Maxwell Anderson Ielpo do Amaral </p>
  </div>
  <div class="quarto-title-meta-contents">
        <p class="affiliation">
            Instituto Federal de Educação, Ciência e Tecnologia da Paraíba (IFPB) — Campus João Pessoa
          </p>
      </div>
  </div>

<div class="quarto-title-meta">

      
    <div>
    <div class="quarto-title-meta-heading">Data de Publicação</div>
    <div class="quarto-title-meta-contents">
      <p class="date">20 de outubro de 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Dica</span>📽️ Material da Aula
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li>📄 <a href="../apostila.pdf" target="_blank">Baixar Apostila Completa em PDF</a></li>
<li>🧪 <a href="../../assets/simuladores/" target="_blank">Galeria de Simuladores Interativos</a></li>
<li>🚀 <a href="https://colab.research.google.com/github/maxwellamaral/aula-quantum/blob/main/notebooks/05-interference.ipynb" target="_blank">Executar no Google Colab</a></li>
</ul>
</div>
</div>
<section id="aula-07-interferência-quântica-e-algoritmo-de-deutsch-jozsa" class="level1">
<h1>Aula 07 — Interferência Quântica e Algoritmo de Deutsch-Jozsa</h1>
</section>
<section id="interferência-quântica-e-algoritmos" class="level1">
<h1>Interferência Quântica e Algoritmos</h1>
<section id="visão-geral" class="level2">
<h2 class="anchored" data-anchor-id="visão-geral">📖 Visão Geral</h2>
<p>Bem-vindo ao notebook mais avançado desta série! Aqui vamos mergulhar nos mecanismos que tornam os <strong>algoritmos quânticos</strong> fundamentalmente diferentes (e mais poderosos) que os clássicos.</p>
<section id="o-que-você-vai-aprender" class="level3">
<h3 class="anchored" data-anchor-id="o-que-você-vai-aprender">🎯 O Que Você Vai Aprender</h3>
<ol type="1">
<li><strong>Phase Kickback (Coice de Fase)</strong>
<ul>
<li>O mecanismo “secreto” dos algoritmos quânticos</li>
<li>Como o qubit alvo pode afetar o qubit de controle</li>
<li>Demonstração prática com visualizações</li>
</ul></li>
<li><strong>Algoritmo de Deutsch-Jozsa</strong>
<ul>
<li>Primeiro algoritmo a demonstrar vantagem quântica</li>
<li>Resolve um problema com UMA consulta (vs.&nbsp;exponencialmente muitas)</li>
<li>Implementação completa do zero</li>
</ul></li>
</ol>
</section>
<section id="pré-requisitos" class="level3">
<h3 class="anchored" data-anchor-id="pré-requisitos">📚 Pré-requisitos</h3>
<p>Antes de continuar, certifique-se de que você entende:</p>
<ul>
<li>✅ <strong>Superposição</strong> - de <a href="01-intro.ipynb">01-intro.ipynb</a></li>
<li>✅ <strong>Emaranhamento</strong> - de <a href="02-teletransport.ipynb">02-teletransport.ipynb</a></li>
<li>✅ <strong>Porta Hadamard</strong> - de <a href="04-Hadamard-experiment.ipynb">04-Hadamard-experiment.ipynb</a></li>
<li>✅ <strong>Interferência básica</strong> - H × H = I</li>
</ul>
</section>
<section id="nível-de-dificuldade" class="level3">
<h3 class="anchored" data-anchor-id="nível-de-dificuldade">🎓 Nível de Dificuldade</h3>
<p><strong>Intermediário a Avançado</strong> - Este notebook assume familiaridade com:</p>
<ul>
<li>Notação de Dirac (<span class="math inline">\(|0\rangle, |1\rangle, |+\rangle, |-\rangle\)</span>)</li>
<li>Portas quânticas básicas (H, X, CNOT)</li>
<li>Conceito de fase em estados quânticos</li>
<li>Produto tensorial (<span class="math inline">\(\otimes\)</span>)</li>
</ul>
</section>
<section id="por-que-este-conteúdo-é-importante" class="level3">
<h3 class="anchored" data-anchor-id="por-que-este-conteúdo-é-importante">💡 Por Que Este Conteúdo é Importante?</h3>
<p><strong>Phase Kickback</strong> é o “ingrediente secreto” que faz algoritmos como:</p>
<ul>
<li>🔍 <strong>Grover</strong> (busca quântica) - quadraticamente mais rápido</li>
<li>🔢 <strong>Shor</strong> (fatoração) - exponencialmente mais rápido (quebra RSA!)</li>
<li>⚗️ <strong>QPE</strong> (estimação de fase) - base da química quântica</li>
</ul>
<p>Sem entender kickback, algoritmos quânticos parecem “mágica”. Com esse entendimento, você verá a lógica elegante por trás da supremacia quântica.</p>
</section>
<section id="estrutura-do-notebook" class="level3">
<h3 class="anchored" data-anchor-id="estrutura-do-notebook">🗺️ Estrutura do Notebook</h3>
<pre class="text"><code>1. Phase Kickback
   ├── Conceito e Analogia
   ├── Matemática Detalhada
   ├── Demonstração Prática
   └── Visualizações (Bloch + Q-Sphere)

2. Deutsch-Jozsa
   ├── Definição do Problema
   ├── Oráculos (Constante vs. Balanceado)
   ├── Implementação Completa
   └── Análise de Resultados

3. Resumo e Próximos Passos
   └── Conexões com Algoritmos Avançados</code></pre>
<hr>
<p><strong>Dica:</strong> Execute as células em ordem sequencial. Cada visualização ajuda a construir a intuição para o próximo conceito!</p>
<hr>
</section>
</section>
<section id="phase-kickback-e-o-algoritmo-de-deutsch-jozsa" class="level2">
<h2 class="anchored" data-anchor-id="phase-kickback-e-o-algoritmo-de-deutsch-jozsa">Phase Kickback e o Algoritmo de Deutsch-Jozsa</h2>
<p>Vamos mergulhar no mecanismo que faz os algoritmos quânticos funcionarem.</p>
<p>Até agora, a intuição foi: “O qubit de controle manda no qubit alvo”.</p>
<p>Lembra da porta CNOT em <a href="01-intro.ipynb">01-intro.ipynb</a>?</p>
<p>No <strong>Phase Kickback</strong> (Coice de Fase), descobrimos que a relação é uma via de mão dupla. O qubit alvo pode alterar o estado do qubit de controle.</p>
<p>É aqui que a “mágica” acontece.</p>
<hr>
<section id="o-conceito-phase-kickback-o-recuo-da-arma" class="level3">
<h3 class="anchored" data-anchor-id="o-conceito-phase-kickback-o-recuo-da-arma">1. O Conceito: Phase Kickback (O Recuo da Arma)</h3>
<p>Imagine que você está disparando uma arma de fogo:</p>
<ol type="1">
<li><strong>Ação:</strong> Você (Controle) aperta o gatilho.</li>
<li><strong>Efeito:</strong> A bala (Alvo) sai.</li>
<li><strong>Reação:</strong> O seu ombro sente um “coice” ou recuo para trás.</li>
</ol>
<p>Na computação quântica, se prepararmos o qubit alvo de uma maneira específica, a operação “bate” nele e volta, alterando a fase do controle.</p>
<section id="a-matemática-simplificada" class="level4">
<h4 class="anchored" data-anchor-id="a-matemática-simplificada">A Matemática (Simplificada)</h4>
<p>Vamos usar a porta CNOT.</p>
<ul>
<li>Alvo Normal (<span class="math inline">\(|0\rangle\)</span> ou <span class="math inline">\(|1\rangle\)</span>): O CNOT inverte o valor (0 vira 1).</li>
<li>Alvo em Autestado (<span class="math inline">\(|-\rangle\)</span>): O estado <span class="math inline">\(|-\rangle\)</span> (que é <span class="math inline">\(H|1\rangle\)</span>) é especial para a porta X (NOT).</li>
</ul>
<p><span class="math display">\[X|-\rangle = -|-\rangle\]</span></p>
<p>(A porta X apenas adiciona um sinal negativo, uma fase de 180º).</p>
<hr>
<section id="mais-sobre-o-estado--rangle" class="level5">
<h5 class="anchored" data-anchor-id="mais-sobre-o-estado--rangle">Mais sobre o estado <span class="math inline">\(|-\rangle\)</span></h5>
<p>O estado <span class="math inline">\(|-\rangle\)</span> é um dos <strong>estados de superposição fundamentais</strong> em computação quântica. Vou explicar:</p>
<p><strong>O que é <span class="math inline">\(|-\rangle\)</span>?</strong></p>
<p><span class="math display">\[|-\rangle = \frac{|0\rangle - |1\rangle}{\sqrt{2}}\]</span></p>
<p>É uma <strong>superposição</strong> de <span class="math inline">\(|0\rangle\)</span> e <span class="math inline">\(|1\rangle\)</span> com uma diferença de fase de 180° entre eles (note o sinal <strong>negativo</strong>).</p>
<p><strong>Por que <span class="math inline">\(|-\rangle = H|1\rangle\)</span>?</strong></p>
<p>Aplicando a porta Hadamard (H) ao estado <span class="math inline">\(|1\rangle\)</span>:</p>
<p><span class="math display">\[H|1\rangle = H \begin{pmatrix} 0 \\ 1 \end{pmatrix} = \frac{1}{\sqrt{2}} \begin{pmatrix} 1 &amp; 1 \\ 1 &amp; -1 \end{pmatrix} \begin{pmatrix} 0 \\ 1 \end{pmatrix}\]</span></p>
<p><span class="math display">\[= \frac{1}{\sqrt{2}} \begin{pmatrix} 1 \\ -1 \end{pmatrix} = \frac{|0\rangle - |1\rangle}{\sqrt{2}} = |-\rangle\]</span></p>
</section>
<section id="comparação-com-rangle" class="level5">
<h5 class="anchored" data-anchor-id="comparação-com-rangle">Comparação com <span class="math inline">\(|+\rangle\)</span></h5>
<ul>
<li><span class="math inline">\(|+\rangle = H|0\rangle = \frac{|0\rangle + |1\rangle}{\sqrt{2}}\)</span> (sinal <strong>positivo</strong>)</li>
<li><span class="math inline">\(|-\rangle = H|1\rangle = \frac{|0\rangle - |1\rangle}{\sqrt{2}}\)</span> (sinal <strong>negativo</strong>)</li>
</ul>
<hr>
</section>
<section id="por-que--rangle-é-especial-para-o-phase-kickback" class="level5">
<h5 class="anchored" data-anchor-id="por-que--rangle-é-especial-para-o-phase-kickback">Por que <span class="math inline">\(|-\rangle\)</span> é especial para o Phase Kickback?</h5>
<p>O estado <span class="math inline">\(|-\rangle\)</span> é um <strong>autoestado</strong> da porta X (NOT):</p>
<p><span class="math display">\[X|-\rangle = -|-\rangle\]</span></p>
<p>A porta X apenas adiciona uma fase global negativa, mas não muda o estado. Essa propriedade permite que a fase “retorne” para o qubit de controle no CNOT, criando o efeito de <strong>Phase Kickback</strong>.</p>
<p>Quando aplicamos CNOT com o alvo em <span class="math inline">\(|-\rangle\)</span>:</p>
<ul>
<li>Se o controle for <span class="math inline">\(|0\rangle\)</span>, nada acontece.</li>
<li>Se o controle for <span class="math inline">\(|1\rangle\)</span>, o alvo ganha um sinal de menos (<span class="math inline">\(-\)</span>).</li>
<li>Como o alvo não mudou visualmente (continua <span class="math inline">\(|-\rangle\)</span>), esse sinal de menos migra para o qubit de controle.</li>
</ul>
<p>Resultado: O controle, que era <span class="math inline">\(|+\rangle\)</span>, vira <span class="math inline">\(|-\rangle\)</span>. O alvo não muda.</p>
</section>
</section>
<section id="código-completo-do-phase-kickback" class="level4">
<h4 class="anchored" data-anchor-id="código-completo-do-phase-kickback">Código completo do Phase Kickback</h4>
<p>Segue o código completo para demonstrar o Phase Kickback usando Qiskit. Logo após, faremos uma análise detalhada de cada etapa.</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> qiskit <span class="im">import</span> QuantumCircuit, transpile</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> qiskit_aer <span class="im">import</span> AerSimulator</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> qiskit.quantum_info <span class="im">import</span> Statevector</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> qiskit.visualization <span class="im">import</span> plot_bloch_multivector, plot_state_qsphere</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Criar circuito com 2 qubits</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>qc <span class="op">=</span> QuantumCircuit(<span class="dv">2</span>, <span class="dv">1</span>)  <span class="co"># 2 Qubits, 1 Bit clássico</span></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>qc.draw(<span class="st">"mpl"</span>)</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a><span class="co"># 1. PREPARAÇÃO</span></span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Colocar o Qubit 0 (Controle) em Superposição |+&gt;</span></span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>qc.h(<span class="dv">0</span>)</span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Colocar o Qubit 1 (Alvo) no estado |- &gt;</span></span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Para isso: aplicamos X (vira 1) e depois H (vira menos)</span></span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a>qc.x(<span class="dv">1</span>)</span>
<span id="cb3-12"><a href="#cb3-12" aria-hidden="true" tabindex="-1"></a>qc.h(<span class="dv">1</span>)</span>
<span id="cb3-13"><a href="#cb3-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-14"><a href="#cb3-14" aria-hidden="true" tabindex="-1"></a><span class="co"># 2. O KICKBACK</span></span>
<span id="cb3-15"><a href="#cb3-15" aria-hidden="true" tabindex="-1"></a><span class="co"># Aplicamos CNOT. O alvo (q1) está em |-&gt;.</span></span>
<span id="cb3-16"><a href="#cb3-16" aria-hidden="true" tabindex="-1"></a><span class="co"># Isso deve fazer o q0 virar |-&gt; "por tabela".</span></span>
<span id="cb3-17"><a href="#cb3-17" aria-hidden="true" tabindex="-1"></a>qc.cx(<span class="dv">0</span>, <span class="dv">1</span>)</span>
<span id="cb3-18"><a href="#cb3-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-19"><a href="#cb3-19" aria-hidden="true" tabindex="-1"></a><span class="co"># 3. VERIFICAÇÃO</span></span>
<span id="cb3-20"><a href="#cb3-20" aria-hidden="true" tabindex="-1"></a><span class="co"># Como saber se q0 virou |-&gt;?</span></span>
<span id="cb3-21"><a href="#cb3-21" aria-hidden="true" tabindex="-1"></a><span class="co"># Se aplicarmos H novamente:</span></span>
<span id="cb3-22"><a href="#cb3-22" aria-hidden="true" tabindex="-1"></a><span class="co"># H em |+&gt; volta para 0</span></span>
<span id="cb3-23"><a href="#cb3-23" aria-hidden="true" tabindex="-1"></a><span class="co"># H em |-&gt; volta para 1</span></span>
<span id="cb3-24"><a href="#cb3-24" aria-hidden="true" tabindex="-1"></a>qc.h(<span class="dv">0</span>)</span>
<span id="cb3-25"><a href="#cb3-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-26"><a href="#cb3-26" aria-hidden="true" tabindex="-1"></a><span class="co"># Medimos APENAS o qubit de controle (q0)</span></span>
<span id="cb3-27"><a href="#cb3-27" aria-hidden="true" tabindex="-1"></a>qc.measure(<span class="dv">0</span>, <span class="dv">0</span>)</span>
<span id="cb3-28"><a href="#cb3-28" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-29"><a href="#cb3-29" aria-hidden="true" tabindex="-1"></a><span class="co"># Executar</span></span>
<span id="cb3-30"><a href="#cb3-30" aria-hidden="true" tabindex="-1"></a>simulador <span class="op">=</span> AerSimulator()</span>
<span id="cb3-31"><a href="#cb3-31" aria-hidden="true" tabindex="-1"></a>job <span class="op">=</span> simulador.run(transpile(qc, simulador), shots<span class="op">=</span><span class="dv">1000</span>)</span>
<span id="cb3-32"><a href="#cb3-32" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Resultado do Controle:"</span>, job.result().get_counts())</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<pre><code>Resultado do Controle: {'1': 1000}
</code></pre>
<pre class="{python} {pyodide-python}"><code>
# Visualizar o circuito completo
qc.draw('mpl')</code></pre>
</section>
<section id="demonstração-detalhada-de-phase-kickback" class="level4">
<h4 class="anchored" data-anchor-id="demonstração-detalhada-de-phase-kickback">Demonstração detalhada de Phase Kickback</h4>
<p>Vamos provar que o qubit de controle muda sem que nenhuma porta toque nele diretamente.</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb6"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Criar circuito com 2 qubits</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>qc <span class="op">=</span> QuantumCircuit(<span class="dv">2</span>, <span class="dv">1</span>) <span class="co"># 2 Qubits, 1 Bit clássico</span></span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Desenhar o circuito</span></span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>qc.draw(<span class="st">'mpl'</span>)</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<p>Matematicamente, os estados dos qubits, quando criados, são:</p>
<ul>
<li>Qubit 0 (Controle): <span class="math inline">\(|0\rangle\)</span></li>
<li>Qubit 1 (Alvo): <span class="math inline">\(|0\rangle\)</span></li>
</ul>
<p>Estes estados iniciais representam <span class="math inline">\(|00\rangle\)</span> do registrador quântico.</p>
</section>
</section>
<section id="o-estado-inicial" class="level3">
<h3 class="anchored" data-anchor-id="o-estado-inicial">O Estado Inicial</h3>
<pre class="{python} {pyodide-python}"><code>
# 1. PREPARAÇÃO
# Colocar o Qubit 0 (Controle) em Superposição |+&gt;
qc.h(0)

# Colocar o Qubit 1 (Alvo) no estado |- &gt; 
# Para isso: aplicamos X (vira 1) e depois H (vira menos)
qc.x(1)
qc.h(1)

# Desenhar o circuito
qc.draw('mpl')</code></pre>
<section id="demonstração-matemática-preparação-do-estado-inicial" class="level4">
<h4 class="anchored" data-anchor-id="demonstração-matemática-preparação-do-estado-inicial">Demonstração Matemática: Preparação do Estado Inicial</h4>
<p>O estado inicial preparado após a aplicação das portas Hadamard é:</p>
<p><span class="math display">\[|\psi_0\rangle = |+\rangle \otimes |-\rangle\]</span></p>
<p>Expandindo cada componente:</p>
<p><span class="math display">\[|+\rangle = \frac{|0\rangle + |1\rangle}{\sqrt{2}}\]</span></p>
<p><span class="math display">\[|-\rangle = \frac{|0\rangle - |1\rangle}{\sqrt{2}}\]</span></p>
<p>Portanto, o estado completo é:</p>
<p><span class="math display">\[|\psi_0\rangle = \frac{1}{\sqrt{2}}(|0\rangle + |1\rangle) \otimes \frac{1}{\sqrt{2}}(|0\rangle - |1\rangle)\]</span></p>
<p>Usando a representação matricial dos estados:</p>
<p><span class="math display">\[|0\rangle = \begin{pmatrix} 1 \\ 0 \end{pmatrix}, \quad |1\rangle = \begin{pmatrix} 0 \\ 1 \end{pmatrix}\]</span></p>
<p><span class="math display">\[|+\rangle = \frac{1}{\sqrt{2}}\begin{pmatrix} 1 \\ 1 \end{pmatrix}, \quad |-\rangle = \frac{1}{\sqrt{2}}\begin{pmatrix} 1 \\ -1 \end{pmatrix}\]</span></p>
<p>O produto tensorial <span class="math inline">\(|\psi_0\rangle = |+\rangle \otimes |-\rangle\)</span> é calculado como: <span class="math display">\[|\psi_0\rangle = \frac{1}{\sqrt{2}}\begin{pmatrix} 1 \\ 1 \end{pmatrix} \otimes \frac{1}{\sqrt{2}}\begin{pmatrix} 1 \\ -1 \end{pmatrix}\]</span></p>
<p>Primeiro, combinamos os coeficientes escalares:</p>
<p><span class="math display">\[= \frac{1}{\sqrt{2}} \cdot \frac{1}{\sqrt{2}} \begin{pmatrix} 1 \\ 1 \end{pmatrix} \otimes \begin{pmatrix} 1 \\ -1 \end{pmatrix} = \frac{1}{2}\begin{pmatrix} 1 \\ 1 \end{pmatrix} \otimes \begin{pmatrix} 1 \\ -1 \end{pmatrix}\]</span></p>
<p>Agora aplicamos a definição do produto tensorial (produto de Kronecker). Para dois vetores <span class="math inline">\(\mathbf{u} = \begin{pmatrix} u_1 \\ u_2 \end{pmatrix}\)</span> e <span class="math inline">\(\mathbf{v} = \begin{pmatrix} v_1 \\ v_2 \end{pmatrix}\)</span>:</p>
<p><span class="math display">\[\mathbf{u} \otimes \mathbf{v} = \begin{pmatrix} u_1 \mathbf{v} \\ u_2 \mathbf{v} \end{pmatrix} = \begin{pmatrix} u_1 v_1 \\ u_1 v_2 \\ u_2 v_1 \\ u_2 v_2 \end{pmatrix}\]</span></p>
<p>Aplicando ao nosso caso onde <span class="math inline">\(u_1 = 1\)</span>, <span class="math inline">\(u_2 = 1\)</span>, <span class="math inline">\(v_1 = 1\)</span>, <span class="math inline">\(v_2 = -1\)</span>:</p>
<p><span class="math display">\[\begin{pmatrix} 1 \\ 1 \end{pmatrix} \otimes \begin{pmatrix} 1 \\ -1 \end{pmatrix} = \begin{pmatrix} 1 \cdot \begin{pmatrix} 1 \\ -1 \end{pmatrix} \\ 1 \cdot \begin{pmatrix} 1 \\ -1 \end{pmatrix} \end{pmatrix} = \begin{pmatrix} 1 \cdot 1 \\ 1 \cdot (-1) \\ 1 \cdot 1 \\ 1 \cdot (-1) \end{pmatrix} = \begin{pmatrix} 1 \\ -1 \\ 1 \\ -1 \end{pmatrix}\]</span></p>
<p>Multiplicando pelo coeficiente <span class="math inline">\(\frac{1}{2}\)</span>: <span class="math display">\[|\psi_0\rangle = \frac{1}{2}\begin{pmatrix} 1 \\ 1 \end{pmatrix} \otimes \begin{pmatrix} 1 \\ -1 \end{pmatrix}\]</span></p>
<p>Se você ainda não entendeu, vamos calcular o produto tensorial passo a passo. O produto tensorial de dois vetores coluna funciona da seguinte forma:</p>
<p><strong>Passo 1:</strong> Pegue o primeiro elemento do primeiro vetor (que é <span class="math inline">\(1\)</span>) e multiplique-o por todo o segundo vetor:</p>
<p><span class="math display">\[1 \cdot \begin{pmatrix} 1 \\ -1 \end{pmatrix} = \begin{pmatrix} 1 \cdot 1 \\ 1 \cdot (-1) \end{pmatrix} = \begin{pmatrix} 1 \\ -1 \end{pmatrix}\]</span></p>
<p><strong>Passo 2:</strong> Pegue o segundo elemento do primeiro vetor (que também é <span class="math inline">\(1\)</span>) e multiplique-o por todo o segundo vetor:</p>
<p><span class="math display">\[1 \cdot \begin{pmatrix} 1 \\ -1 \end{pmatrix} = \begin{pmatrix} 1 \cdot 1 \\ 1 \cdot (-1) \end{pmatrix} = \begin{pmatrix} 1 \\ -1 \end{pmatrix}\]</span></p>
<p><strong>Passo 3:</strong> Empilhe os resultados verticalmente para formar um vetor de 4 elementos:</p>
<p><span class="math display">\[\begin{pmatrix} 1 \\ 1 \end{pmatrix} \otimes \begin{pmatrix} 1 \\ -1 \end{pmatrix} = \begin{pmatrix} \text{resultado do passo 1} \\ \text{resultado do passo 2} \end{pmatrix} = \begin{pmatrix} 1 \\ -1 \\ 1 \\ -1 \end{pmatrix}\]</span></p>
<p><strong>Passo 4:</strong> Multiplique o resultado pelo coeficiente <span class="math inline">\(\frac{1}{2}\)</span>:</p>
<p><span class="math display">\[|\psi_0\rangle = \frac{1}{2}\begin{pmatrix} 1 \\ -1 \\ 1 \\ -1 \end{pmatrix} = \begin{pmatrix} \frac{1}{2} \cdot 1 \\ \frac{1}{2} \cdot (-1) \\ \frac{1}{2} \cdot 1 \\ \frac{1}{2} \cdot (-1) \end{pmatrix} = \begin{pmatrix} \frac{1}{2} \\ -\frac{1}{2} \\ \frac{1}{2} \\ -\frac{1}{2} \end{pmatrix}\]</span></p>
<p>Lembre-se que se expandirmos em termos da base computacional <span class="math inline">\(\{|00\rangle, |01\rangle, |10\rangle, |11\rangle\}\)</span>:</p>
<p><span class="math display">\[|00\rangle = \begin{pmatrix} 1 \\ 0 \\ 0 \\ 0 \end{pmatrix}, \quad |01\rangle = \begin{pmatrix} 0 \\ 1 \\ 0 \\ 0 \end{pmatrix}, \quad |10\rangle = \begin{pmatrix} 0 \\ 0 \\ 1 \\ 0 \end{pmatrix}, \quad |11\rangle = \begin{pmatrix} 0 \\ 0 \\ 0 \\ 1 \end{pmatrix}\]</span></p>
<p>Lembra disso acima? Se não, volte para a seção de produto tensorial em <a href="00-math.ipynb">00-math.ipynb</a>.</p>
<p>Portanto, o vetor <span class="math inline">\(\frac{1}{2}\begin{pmatrix} 1 \\ -1 \\ 1 \\ -1 \end{pmatrix}\)</span> pode ser escrito como:</p>
<p><span class="math display">\[|\psi_0\rangle = \frac{1}{2} \cdot 1 \cdot \begin{pmatrix} 1 \\ 0 \\ 0 \\ 0 \end{pmatrix} + \frac{1}{2} \cdot (-1) \cdot \begin{pmatrix} 0 \\ 1 \\ 0 \\ 0 \end{pmatrix} + \frac{1}{2} \cdot 1 \cdot \begin{pmatrix} 0 \\ 0 \\ 1 \\ 0 \end{pmatrix} + \frac{1}{2} \cdot (-1) \cdot \begin{pmatrix} 0 \\ 0 \\ 0 \\ 1 \end{pmatrix} \implies\]</span></p>
<p><span class="math display">\[|\psi_0\rangle = \frac{1}{2} \cdot 1 \cdot |00\rangle + \frac{1}{2} \cdot (-1) \cdot |01\rangle + \frac{1}{2} \cdot 1 \cdot |10\rangle + \frac{1}{2} \cdot (-1) \cdot |11\rangle\]</span></p>
<p>Este vetor corresponde ao estado na base computacional:</p>
<p><span class="math display">\[= \frac{1}{2}(|00\rangle - |01\rangle + |10\rangle - |11\rangle)\]</span></p>
<p>Percebeu como é simples? Provavelmente a notação matemática é assustadora, mas o conceito é simples quando você vê a operação em ação na ponta do lápis.</p>
</section>
</section>
<section id="visualização-estado-inicial-preparado" class="level3">
<h3 class="anchored" data-anchor-id="visualização-estado-inicial-preparado">Visualização: Estado Inicial Preparado</h3>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb8"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Visualizar o estado após preparação</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>estado_inicial <span class="op">=</span> Statevector(qc)</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Estado inicial: </span><span class="sc">{</span>estado_inicial<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>display(plot_bloch_multivector(estado_inicial))</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<pre><code>Estado inicial: Statevector([ 0.5+0.j,  0.5+0.j, -0.5+0.j, -0.5+0.j],
            dims=(2, 2))
</code></pre>
<p>A esfera acima representa <span class="math inline">\(|\psi_0\rangle = |+\rangle \otimes |-\rangle\)</span>.</p>
<section id="o-que-é-a-esfera-de-bloch" class="level4">
<h4 class="anchored" data-anchor-id="o-que-é-a-esfera-de-bloch">O que é a Esfera de Bloch?</h4>
<p>(Relembrando)</p>
<p>A <strong>Esfera de Bloch</strong> é uma representação geométrica tridimensional do estado de um único qubit. Ela é uma ferramenta visual poderosa para entender os estados quânticos e suas transformações.</p>
<p><strong>Características principais:</strong></p>
<ol type="1">
<li><strong>Polos da esfera:</strong>
<ul>
<li><strong>Polo Norte (topo):</strong> Representa o estado <span class="math inline">\(|0\rangle\)</span></li>
<li><strong>Polo Sul (base):</strong> Representa o estado <span class="math inline">\(|1\rangle\)</span></li>
</ul></li>
<li><strong>Equador da esfera:</strong>
<ul>
<li>Contém todos os estados de superposição com fase relativa</li>
<li>O ponto no eixo X positivo representa <span class="math inline">\(H|0\rangle = |+ \rangle = \frac{|0\rangle + |1\rangle}{\sqrt{2}}\)</span></li>
<li>O ponto no eixo X negativo representa <span class="math inline">\(H|1\rangle = |-\rangle = \frac{|0\rangle - |1\rangle}{\sqrt{2}}\)</span></li>
</ul></li>
<li><strong>Interior da esfera:</strong>
<ul>
<li>Apenas a superfície é válida para estados quânticos puros</li>
<li>Pontos no interior representam estados mistos (não se aplicam aqui)</li>
</ul></li>
<li><strong>Vetores (setas rosa):</strong>
<ul>
<li>Mostram o estado atual de cada qubit</li>
<li>A direção do vetor indica a combinação de amplitude e fase</li>
<li>Quanto mais próximo de um polo, maior a probabilidade de medir aquele estado</li>
</ul></li>
</ol>
<p><strong>Por que dois qubits = duas esferas?</strong></p>
<p>Cada qubit individual pode ser visualizado em sua própria esfera de Bloch. Quando temos 2 qubits:</p>
<ul>
<li><strong>Qubit 0 (esquerda):</strong> Mostra o estado do qubit de controle</li>
<li><strong>Qubit 1 (direita):</strong> Mostra o estado do qubit alvo</li>
</ul>
<p><strong>Interpretando o estado preparado (<span class="math inline">\(|+\rangle \otimes |-\rangle\)</span>):</strong></p>
<ul>
<li><strong>Qubit 0:</strong> O vetor aponta para o eixo X positivo → está em <span class="math inline">\(|+\rangle\)</span>
<ul>
<li>Superposição igual entre <span class="math inline">\(|0\rangle\)</span> e <span class="math inline">\(|1\rangle\)</span> com fase positiva</li>
<li>Probabilidades: 50% de medir 0, 50% de medir 1</li>
</ul></li>
<li><strong>Qubit 1:</strong> O vetor aponta para o eixo X negativo → está em <span class="math inline">\(|-\rangle\)</span>
<ul>
<li>Superposição igual entre <span class="math inline">\(|0\rangle\)</span> e <span class="math inline">\(|1\rangle\)</span> com fase negativa</li>
<li>Probabilidades: 50% de medir 0, 50% de medir 1</li>
<li>O sinal negativo é uma diferença de fase de 180° entre os componentes</li>
</ul></li>
</ul>
<p><strong>O que observar nas visualizações:</strong></p>
<p>Quando aplicarmos o CNOT (Phase Kickback), veremos:</p>
<ul>
<li><strong>Qubit 0:</strong> O vetor vai <strong>girar</strong> do eixo X+ para o eixo X- (de <span class="math inline">\(|+\rangle\)</span> para <span class="math inline">\(|-\rangle\)</span>)</li>
<li><strong>Qubit 1:</strong> O vetor <strong>permanece no mesmo lugar</strong> (continua em <span class="math inline">\(|-\rangle\)</span>)</li>
</ul>
<p>Essa rotação do qubit de controle <strong>sem que nenhuma porta aja diretamente sobre ele</strong> é a essência do Phase Kickback!</p>
</section>
</section>
</section>
<section id="q-sphere" class="level2">
<h2 class="anchored" data-anchor-id="q-sphere">Q-Sphere</h2>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb10"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"</span><span class="ch">\n</span><span class="st">Q-Sphere mostrando ambos os qubits:"</span>)</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>display(plot_state_qsphere(estado_inicial))</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<pre><code>
Q-Sphere mostrando ambos os qubits:
</code></pre>
<section id="o-que-é-a-q-sphere-esfera-quântica" class="level4">
<h4 class="anchored" data-anchor-id="o-que-é-a-q-sphere-esfera-quântica">O que é a Q-Sphere (Esfera Quântica)?</h4>
<p>A <strong>Q-Sphere</strong> é outra visualização poderosa para sistemas quânticos, especialmente útil para visualizar múltiplos qubits simultaneamente. Diferente da Esfera de Bloch que mostra qubits individuais, a Q-Sphere mostra o <strong>estado completo do sistema</strong>.</p>
<p><strong>Características principais:</strong></p>
<ol type="1">
<li><strong>Estrutura da esfera:</strong>
<ul>
<li>Cada <strong>ponto na superfície</strong> representa um possível estado da base computacional</li>
<li>Para 2 qubits: 4 pontos (|00⟩, |01⟩, |10⟩, |11⟩)</li>
<li>Para 3 qubits: 8 pontos (|000⟩, |001⟩, |010⟩, |011⟩, |100⟩, |101⟩, |110⟩, |111⟩)</li>
</ul></li>
<li><strong>Tamanho das esferas (círculos):</strong>
<ul>
<li>O <strong>diâmetro de cada círculo</strong> representa a <strong>amplitude</strong> (probabilidade) daquele estado</li>
<li>Círculos maiores = maior probabilidade de medir aquele estado</li>
<li>Círculos menores = menor probabilidade</li>
<li>Sem círculo = amplitude zero (não contribui para o estado)</li>
</ul></li>
<li><strong>Cores dos círculos:</strong>
<ul>
<li>Representam a <strong>fase</strong> do estado quântico</li>
<li><strong>Rosa/Magenta</strong>: Fase positiva (0°)</li>
<li><strong>Verde/Ciano</strong>: Fase negativa (180°) ou outras fases intermediárias</li>
<li>A cor indica a fase relativa entre os diferentes componentes do estado</li>
</ul></li>
<li><strong>Posição na esfera:</strong>
<ul>
<li>A distribuição dos pontos na superfície segue uma convenção geométrica</li>
<li>Estados relacionados ficam próximos na esfera</li>
</ul></li>
</ol>
<p><strong>Interpretando o estado <span class="math inline">\(|+\rangle \otimes |-\rangle\)</span>:</strong></p>
<p>Expandindo matematicamente: <span class="math display">\[|+\rangle \otimes |-\rangle = \frac{1}{2}(|00\rangle - |01\rangle + |10\rangle - |11\rangle)\]</span></p>
<p>Na Q-Sphere, veremos <strong>4 círculos</strong> de tamanhos iguais:</p>
<ul>
<li><strong>|00⟩</strong>: Amplitude <span class="math inline">\(\frac{1}{2}\)</span>, fase positiva (+) → círculo rosa</li>
<li><strong>|01⟩</strong>: Amplitude <span class="math inline">\(\frac{1}{2}\)</span>, fase negativa (-) → círculo verde/ciano</li>
<li><strong>|10⟩</strong>: Amplitude <span class="math inline">\(\frac{1}{2}\)</span>, fase positiva (+) → círculo rosa</li>
<li><strong>|11⟩</strong>: Amplitude <span class="math inline">\(\frac{1}{2}\)</span>, fase negativa (-) → círculo verde/ciano</li>
</ul>
<p>Todos os círculos têm o <strong>mesmo tamanho</strong> porque <span class="math inline">\(|\frac{1}{2}|^2 = \frac{1}{4}\)</span> (cada estado tem 25% de probabilidade de ser medido).</p>
<p>As <strong>cores alternadas</strong> mostram o padrão de fase: positivo para |00⟩ e |10⟩, negativo para |01⟩ e |11⟩.</p>
<p><strong>Q-Sphere vs Esfera de Bloch:</strong></p>
<table class="caption-top table">
<colgroup>
<col style="width: 38%">
<col style="width: 61%">
</colgroup>
<thead>
<tr class="header">
<th>Q-Sphere</th>
<th>Esfera de Bloch</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Mostra o sistema completo (todos os qubits juntos)</td>
<td>Mostra cada qubit individualmente</td>
</tr>
<tr class="even">
<td>Revela correlações e emaranhamento</td>
<td>Limitada a 1 qubit por esfera</td>
</tr>
<tr class="odd">
<td>Exibe todas as amplitudes e fases simultaneamente</td>
<td>Mostra apenas o estado reduzido de um qubit</td>
</tr>
<tr class="even">
<td>Ideal para ver interferência quântica</td>
<td>Ideal para visualizar transformações de um único qubit</td>
</tr>
</tbody>
</table>
<p><strong>O que observar nas visualizações:</strong></p>
<p>Quando aplicarmos o CNOT (Phase Kickback), na Q-Sphere veremos:</p>
<ul>
<li>Os <strong>tamanhos dos círculos permanecerão os mesmos</strong> (probabilidades não mudam)</li>
<li>As <strong>cores mudarão</strong> em alguns estados (as fases serão alteradas)</li>
<li>Especificamente, veremos uma reorganização do padrão de cores mostrando que a fase do sistema mudou</li>
</ul>
<p>Essa mudança de fase sem alterar probabilidades é a assinatura característica do <strong>Phase Kickback</strong>!</p>
<pre class="{python} {pyodide-python}"><code>
# 🌐 Visualização INTERATIVA da Q-Sphere
# Importar a função do módulo quantum_viz (localizado em ../src)
import sys
from pathlib import Path
for p in [Path.cwd(), Path.cwd().parent, Path.cwd().parent.parent]:
    if (p / "src").is_dir() and str(p / "src") not in sys.path:
        sys.path.insert(0, str(p / "src"))
from quantum_viz import plot_qsphere_interactive

# 🎨 Criar e exibir a visualização
print("\n🌐 Q-Sphere INTERATIVA:")
print("   → Magenta = Fase positiva (+)")
print("   → Ciano = Fase negativa (-)")
print("   → Tamanho = Probabilidade\n")

# A função plot_qsphere_interactive salva automaticamente e abre no navegador
fig = plot_qsphere_interactive(estado_inicial)</code></pre>
<pre><code>
🌐 Q-Sphere INTERATIVA:
   → Magenta = Fase positiva (+)
   → Ciano = Fase negativa (-)
   → Tamanho = Probabilidade

✅ Visualização 3D salva em: e:\temp\quantum\notebooks\qsphere_interativa.html
   Abrindo no navegador...

💡 Dica: Você pode arrastar, girar e dar zoom na esfera!
   O arquivo HTML pode ser aberto a qualquer momento.
</code></pre>
<pre class="{python} {pyodide-python}"><code>
# 2. O KICKBACK
# Aplicamos CNOT. O alvo (q1) está em |-&gt;.
# Isso deve fazer o q0 virar |-&gt; "por tabela".
qc.cx(0, 1)
</code></pre>
</section>
<section id="demonstração-matemática-o-phase-kickback" class="level4">
<h4 class="anchored" data-anchor-id="demonstração-matemática-o-phase-kickback">Demonstração Matemática: O Phase Kickback</h4>
<p>Aplicando CNOT ao estado <span class="math inline">\(|\psi_0\rangle\)</span>:</p>
<p>A porta CNOT age como: <span class="math inline">\(\text{CNOT}|c,t\rangle = |c, c \oplus t\rangle\)</span></p>
<p>Mas quando o alvo está em <span class="math inline">\(|-\rangle\)</span>, temos uma propriedade especial:</p>
<p><span class="math display">\[\text{CNOT}|c\rangle \otimes |-\rangle = (-1)^c |c\rangle \otimes |-\rangle\]</span></p>
<p>Aplicando ao nosso estado:</p>
<p><span class="math display">\[|\psi_1\rangle = \text{CNOT}|\psi_0\rangle = \text{CNOT}\left[\frac{1}{\sqrt{2}}(|0\rangle + |1\rangle) \otimes |-\rangle\right]\]</span></p>
<p><span class="math display">\[= \frac{1}{\sqrt{2}}[\text{CNOT}(|0\rangle \otimes |-\rangle) + \text{CNOT}(|1\rangle \otimes |-\rangle)]\]</span></p>
<p><span class="math display">\[= \frac{1}{\sqrt{2}}[|0\rangle \otimes |-\rangle + (-1)|1\rangle \otimes |-\rangle]\]</span></p>
<p><span class="math display">\[= \frac{1}{\sqrt{2}}(|0\rangle - |1\rangle) \otimes |-\rangle = |-\rangle \otimes |-\rangle\]</span></p>
<p><strong>Conclusão:</strong> O qubit de controle mudou de <span class="math inline">\(|+\rangle\)</span> para <span class="math inline">\(|-\rangle\)</span> sem que nenhuma porta tenha agido diretamente sobre ele!</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb15"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Visualizar após o CNOT (Phase Kickback aconteceu)</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>estado_apos_kickback <span class="op">=</span> Statevector(qc)</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Estado após CNOT: </span><span class="sc">{</span>estado_apos_kickback<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"</span><span class="ch">\n</span><span class="st">Esfera de Bloch - Note a mudança de fase no qubit 0:"</span>)</span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>display(plot_bloch_multivector(estado_apos_kickback))</span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"</span><span class="ch">\n</span><span class="st">Q-Sphere:"</span>)</span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a>display(plot_state_qsphere(estado_apos_kickback))</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<pre><code>Estado após CNOT: Statevector([ 0.5+0.j, -0.5+0.j, -0.5+0.j,  0.5+0.j],
            dims=(2, 2))

Esfera de Bloch - Note a mudança de fase no qubit 0:
</code></pre>
<pre><code>
Q-Sphere:
</code></pre>
</section>
<section id="visualização-após-o-phase-kickback-cnot" class="level4">
<h4 class="anchored" data-anchor-id="visualização-após-o-phase-kickback-cnot">Visualização: Após o Phase Kickback (CNOT)</h4>
<pre class="{python} {pyodide-python}"><code>
# 3. VERIFICAÇÃO
# Como saber se q0 virou |-&gt;?
# Se aplicarmos H novamente:
# H em |+&gt; volta para 0
# H em |-&gt; volta para 1
qc.h(0)
</code></pre>
</section>
<section id="demonstração-matemática-verificação-com-hadamard" class="level4">
<h4 class="anchored" data-anchor-id="demonstração-matemática-verificação-com-hadamard">Demonstração Matemática: Verificação com Hadamard</h4>
<p>Para verificar que o qubit 0 está em <span class="math inline">\(|-\rangle\)</span>, aplicamos H novamente:</p>
<p><span class="math display">\[H|+\rangle = H \cdot H|0\rangle = |0\rangle\]</span></p>
<p><span class="math display">\[H|-\rangle = H \cdot H|1\rangle = |1\rangle\]</span></p>
<p>Portanto:</p>
<ul>
<li>Se medirmos <strong>0</strong>, o estado antes era <span class="math inline">\(|+\rangle\)</span></li>
<li>Se medirmos <strong>1</strong>, o estado antes era <span class="math inline">\(|-\rangle\)</span></li>
</ul>
<p>Como o Phase Kickback transformou <span class="math inline">\(|+\rangle \to |-\rangle\)</span>, esperamos medir <strong>1</strong> em 100% das vezes!</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb19"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>estado_verificacao <span class="op">=</span> Statevector(qc)</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Estado após verificação (H no q0): </span><span class="sc">{</span>estado_verificacao<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>display(plot_bloch_multivector(estado_verificacao))</span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"</span><span class="ch">\n</span><span class="st">Q-Sphere:"</span>)</span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a>display(plot_state_qsphere(estado_verificacao))</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<pre><code>Estado após verificação (H no q0): Statevector([ 2.29934717e-17+0.j,  7.07106781e-01+0.j, -2.29934717e-17+0.j,
             -7.07106781e-01+0.j],
            dims=(2, 2))
</code></pre>
<pre><code>
Q-Sphere:
</code></pre>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb22"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Medimos APENAS o qubit de controle (q0)</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>qc.measure(<span class="dv">0</span>, <span class="dv">0</span>)</span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Executar</span></span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a>simulador <span class="op">=</span> AerSimulator()</span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a>job <span class="op">=</span> simulador.run(transpile(qc, simulador), shots<span class="op">=</span><span class="dv">1000</span>)</span>
<span id="cb22-7"><a href="#cb22-7" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Resultado do Controle:"</span>, job.result().get_counts())</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<pre><code>Resultado do Controle: {'1': 1000}
</code></pre>
<p><strong>Resultado esperado:</strong> <code>{'1': 1000}</code>. Você mediu 1. Isso prova que o estado antes da medição era <span class="math inline">\(\ket{1}\)</span>. O controle foi alterado pelo alvo!</p>
<hr>
<hr>
</section>
<section id="o-algoritmo-de-deutsch-jozsa" class="level3">
<h3 class="anchored" data-anchor-id="o-algoritmo-de-deutsch-jozsa">2. O Algoritmo de Deutsch-Jozsa</h3>
<p>Agora vamos usar esse “coice” para resolver um problema.</p>
<p><strong>O problema</strong>: Você tem uma função secreta (uma caixa preta) <span class="math inline">\(f(x)\)</span> que recebe bits e cospe 0 ou 1. Você sabe que a função só pode ser de dois tipos:</p>
<ol type="1">
<li><strong>Constante:</strong> Retorna sempre 0 ou sempre 1 (independente da entrada).</li>
<li><strong>Balanceada:</strong> Retorna 0 para metade das entradas e 1 para a outra metade.</li>
</ol>
<p>Para ser mais intuitivo:</p>
<ol type="1">
<li>Imagine que você implemente um vetor com 3 bits de entrada (000 a 111): <code>vetor = [0, 1, 0]</code> por exemplo.</li>
<li>Se o vetor for <code>[0,0,0]</code>, isto é, todos os valores são 0, então a função é <strong>constante</strong>.</li>
<li>Se o vetor for <code>[1,1,1]</code>, isto é, todos os valores são 1, então a função é <strong>constante</strong>.</li>
<li>Se o vetor for <code>[0,1,1]</code>, isto é, alguns dos valores são 0 e outros são 1, então a função é <strong>balanceada</strong>.</li>
<li>A função <span class="math inline">\(f(x)\)</span> verifica se o vetor é constante ou balanceado.</li>
<li>Somente isso.</li>
</ol>
<p><strong>Desafio:</strong> Quantas vezes você precisa testar a caixa para ter 100% de certeza de qual tipo ela é?</p>
<ul>
<li><strong>Computador Clássico:</strong> Se a entrada tem 3 bits, você precisa testar pelo menos <span class="math inline">\(2^{3-1} + 1 = 5\)</span> vezes.</li>
<li><strong>Computador Quântico:</strong> <strong>1 vez.</strong> (Não importa se são 3 bits ou 1 milhão de bits).</li>
</ul>
<p>Vamos ver na prática se isso é verdade?</p>
<section id="teste-com-3-bits-em-computador-clássico" class="level4">
<h4 class="anchored" data-anchor-id="teste-com-3-bits-em-computador-clássico">Teste com 3 bits em computador clássico</h4>
<p>Para os curiosos, resolvi criar à parte o problema da caixa preta para ser utilizado em um computador clássico. Segue o código:</p>
<pre class="{python} {pyodide-python}"><code>
import random

def eh_constante_ou_balanceada(tabela_oculta):
    """
    Entra um vetor parecido com [0,1,0,1,1], este com 5 bits, por exemplo.
    Procura saber se o vetor é constante (só tem 0s ou 1s) ou balanceada (tem 0s e 1s misturados)
    """
    historico_saidas = []
    
    # Testar até o limite do pior caso
    for i in range(limite_pior_caso):
        print(f"Input: {i:03b} -&gt; Output: {tabela_oculta[i]}")
        historico_saidas.append(tabela_oculta[i])
        
        # Se a lista tiver somente 0s ou somente 1s, continuar
        # Caso contrário, já sabemos que é balanceada
        if 0 in historico_saidas and 1 in historico_saidas:
            print("Achamos ambos os valores! A função é balanceada.")
            return "Balanceada"
    
    print("Todos os valores são iguais! A função é constante.")
    return "Constante"

# Utilizando inicialmente 3 bits de entrada (000) para execução rápida e
# simplificação. Experimente depois aumentar para 15 bits. Você verá 
# como é lentooo...
n_bits = 3

# Número total de entradas possíveis (2^n_bits)
total_inputs = 2 ** n_bits

# Vamos fazer o teste contante aqui
tabela_oculta = []                          # Lista que representa a função oculta
valor = random.choice([0, 1])               # Escolhe aleatoriamente 0 ou 1 para toda a lista
tabela_oculta = [valor] * total_inputs      # Preenche a lista com o valor escolhido

print("Tabela oculta (caixa preta):")
print(tabela_oculta)                        # Exibe a tabela oculta

limite_pior_caso = (2 ** (n_bits-1)) + 1    # Limite para o pior caso (metade + 1)

# Aqui começa o teste
# Deverá verificar se a função é constante ou balanceada
# Se todos os valores forem iguais, é constante
# Se encontrar ambos os valores (0 e 1) dentro da lista, é balanceada.
# Obviamente vai ser contante, pois preenchemos assim.

print("\nTestando se a função é constante ou balanceada:")
eh_constante_ou_balanceada(tabela_oculta)
    
# Agora vamos fazer o teste balanceado
tabela_oculta = []                          # Resetar a lista
metade = total_inputs // 2                  # Calcular a metade do total de entradas
tabela_oculta = [0] * metade + [1] * metade # Preencher metade com 0s e metade com 1s
random.shuffle(tabela_oculta)               # Embaralhar a lista para aleatoriedade

print("\nTabela oculta (caixa preta):")
print(tabela_oculta)                        # Exibe a tabela oculta

print("\nTestando se a função é constante ou balanceada:")
eh_constante_ou_balanceada(tabela_oculta)
</code></pre>
<pre><code>Tabela oculta (caixa preta):
[0, 0, 0, 0, 0, 0, 0, 0]

Testando se a função é constante ou balanceada:
Input: 000 -&gt; Output: 0
Input: 001 -&gt; Output: 0
Input: 010 -&gt; Output: 0
Input: 011 -&gt; Output: 0
Input: 100 -&gt; Output: 0
Todos os valores são iguais! A função é constante.

Tabela oculta (caixa preta):
[0, 0, 1, 0, 1, 0, 1, 1]

Testando se a função é constante ou balanceada:
Input: 000 -&gt; Output: 0
Input: 001 -&gt; Output: 0
Input: 010 -&gt; Output: 1
Achamos ambos os valores! A função é balanceada.
</code></pre>
<p>O que observar ao rodar este código:</p>
<ol type="1">
<li><p><strong>No Teste Constante</strong>: O código sempre irá até a tentativa 5 (no caso de 3 bits).</p>
<ul>
<li>Imagine que a função retorna sempre 0.</li>
<li>Ao testar a entrada 1, 2, 3 e 4, você obteve 0, 0, 0, 0.</li>
<li>Você ainda não pode parar. Por quê? Porque uma função balanceada poderia ter seus quatro zeros escondidos justamente nas quatro primeiras posições!</li>
<li>Só ao testar a 5ª vez e obter 0, você prova matematicamente que não existem “uns” suficientes para ela ser balanceada.</li>
</ul></li>
<li><p><strong>No Teste Balanceado</strong>: O código pode parar na tentativa 2 (se você tiver sorte de tirar um 0 e logo depois um 1), ou pode demorar até a tentativa 5 (se você tiver muito azar e tirar todos os 0s antes de achar um 1).</p></li>
</ol>
<p>➡️ Sei que é bem simples o código, mas tente rodar com 15 bits (altere em <code>n_bits</code>) para ver a diferença de tempo! Demora muito!!!</p>
<p>Este código é a prova prática da ineficiência do computador clássico que o Algoritmo de Deutsch-Jozsa resolve com apenas uma consulta com computador quântico!</p>
<hr>
<hr>
</section>
</section>
</section>
<section id="versão-quântica-do-problema" class="level2">
<h2 class="anchored" data-anchor-id="versão-quântica-do-problema">🚀 Versão Quântica do Problema</h2>
<p>Agora vamos implementar o <strong>Algoritmo de Deutsch-Jozsa</strong> - a versão quântica que resolve o mesmo problema com <strong>apenas 1 consulta ao oráculo</strong>!</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb26"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> qiskit <span class="im">import</span> QuantumCircuit, transpile</span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> qiskit_aer <span class="im">import</span> AerSimulator</span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> qiskit.quantum_info <span class="im">import</span> Statevector</span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> qiskit.visualization <span class="im">import</span> plot_bloch_multivector, plot_state_qsphere, plot_histogram</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb27"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="co"># ============================================</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a><span class="co"># DEFINIÇÃO DOS ORÁCULOS</span></span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a><span class="co"># ============================================</span></span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> oraculo_balanceado(n_qubits):</span>
<span id="cb27-6"><a href="#cb27-6" aria-hidden="true" tabindex="-1"></a>    <span class="co">"""</span></span>
<span id="cb27-7"><a href="#cb27-7" aria-hidden="true" tabindex="-1"></a><span class="co">    Cria um circuito que representa uma função BALANCEADA.</span></span>
<span id="cb27-8"><a href="#cb27-8" aria-hidden="true" tabindex="-1"></a><span class="co">    </span></span>
<span id="cb27-9"><a href="#cb27-9" aria-hidden="true" tabindex="-1"></a><span class="co">    Esta função retorna 0 para metade das entradas e 1 para a outra metade.</span></span>
<span id="cb27-10"><a href="#cb27-10" aria-hidden="true" tabindex="-1"></a><span class="co">    Implementação: CNOTs de todos os qubits de entrada para o qubit de saída.</span></span>
<span id="cb27-11"><a href="#cb27-11" aria-hidden="true" tabindex="-1"></a><span class="co">    </span></span>
<span id="cb27-12"><a href="#cb27-12" aria-hidden="true" tabindex="-1"></a><span class="co">    Equivalente quântico de: tabela_oculta = [0]*metade + [1]*metade (embaralhado)</span></span>
<span id="cb27-13"><a href="#cb27-13" aria-hidden="true" tabindex="-1"></a><span class="co">    """</span></span>
<span id="cb27-14"><a href="#cb27-14" aria-hidden="true" tabindex="-1"></a>    qc <span class="op">=</span> QuantumCircuit(n_qubits <span class="op">+</span> <span class="dv">1</span>)</span>
<span id="cb27-15"><a href="#cb27-15" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> qubit <span class="kw">in</span> <span class="bu">range</span>(n_qubits):</span>
<span id="cb27-16"><a href="#cb27-16" aria-hidden="true" tabindex="-1"></a>        qc.cx(qubit, n_qubits) <span class="co"># CNOT de todos inputs para o alvo</span></span>
<span id="cb27-17"><a href="#cb27-17" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> qc</span>
<span id="cb27-18"><a href="#cb27-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-19"><a href="#cb27-19" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> oraculo_constante(n_qubits):</span>
<span id="cb27-20"><a href="#cb27-20" aria-hidden="true" tabindex="-1"></a>    <span class="co">"""</span></span>
<span id="cb27-21"><a href="#cb27-21" aria-hidden="true" tabindex="-1"></a><span class="co">    Cria um circuito que representa uma função CONSTANTE.</span></span>
<span id="cb27-22"><a href="#cb27-22" aria-hidden="true" tabindex="-1"></a><span class="co">    </span></span>
<span id="cb27-23"><a href="#cb27-23" aria-hidden="true" tabindex="-1"></a><span class="co">    Esta função retorna sempre 0 ou sempre 1 (independente da entrada).</span></span>
<span id="cb27-24"><a href="#cb27-24" aria-hidden="true" tabindex="-1"></a><span class="co">    </span></span>
<span id="cb27-25"><a href="#cb27-25" aria-hidden="true" tabindex="-1"></a><span class="co">    Implementação:</span></span>
<span id="cb27-26"><a href="#cb27-26" aria-hidden="true" tabindex="-1"></a><span class="co">    - Retorna sempre 0: não faz nada (circuito identidade)</span></span>
<span id="cb27-27"><a href="#cb27-27" aria-hidden="true" tabindex="-1"></a><span class="co">    - Retorna sempre 1: aplica X no qubit de saída</span></span>
<span id="cb27-28"><a href="#cb27-28" aria-hidden="true" tabindex="-1"></a><span class="co">    </span></span>
<span id="cb27-29"><a href="#cb27-29" aria-hidden="true" tabindex="-1"></a><span class="co">    Equivalente quântico de: tabela_oculta = [0] * total_inputs</span></span>
<span id="cb27-30"><a href="#cb27-30" aria-hidden="true" tabindex="-1"></a><span class="co">                          ou: tabela_oculta = [1] * total_inputs</span></span>
<span id="cb27-31"><a href="#cb27-31" aria-hidden="true" tabindex="-1"></a><span class="co">    """</span></span>
<span id="cb27-32"><a href="#cb27-32" aria-hidden="true" tabindex="-1"></a>    qc <span class="op">=</span> QuantumCircuit(n_qubits <span class="op">+</span> <span class="dv">1</span>)</span>
<span id="cb27-33"><a href="#cb27-33" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Não adicionamos portas, então a saída é constante 0</span></span>
<span id="cb27-34"><a href="#cb27-34" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Para constante 1, descomente a linha abaixo:</span></span>
<span id="cb27-35"><a href="#cb27-35" aria-hidden="true" tabindex="-1"></a>    <span class="co"># qc.x(n_qubits)</span></span>
<span id="cb27-36"><a href="#cb27-36" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> qc</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb28"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="co"># 🎮 EXPERIMENTO INTERATIVO: Teste Ambos os Tipos de Função</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> random</span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> executar_deutsch_jozsa(n_bits, tipo_funcao):</span>
<span id="cb28-6"><a href="#cb28-6" aria-hidden="true" tabindex="-1"></a>    <span class="co">"""</span></span>
<span id="cb28-7"><a href="#cb28-7" aria-hidden="true" tabindex="-1"></a><span class="co">    Executa o Algoritmo de Deutsch-Jozsa para um tipo específico de função.</span></span>
<span id="cb28-8"><a href="#cb28-8" aria-hidden="true" tabindex="-1"></a><span class="co">    </span></span>
<span id="cb28-9"><a href="#cb28-9" aria-hidden="true" tabindex="-1"></a><span class="co">    Args:</span></span>
<span id="cb28-10"><a href="#cb28-10" aria-hidden="true" tabindex="-1"></a><span class="co">        n_bits: Número de bits de entrada</span></span>
<span id="cb28-11"><a href="#cb28-11" aria-hidden="true" tabindex="-1"></a><span class="co">        tipo_funcao: "constante" ou "balanceada"</span></span>
<span id="cb28-12"><a href="#cb28-12" aria-hidden="true" tabindex="-1"></a><span class="co">    """</span></span>
<span id="cb28-13"><a href="#cb28-13" aria-hidden="true" tabindex="-1"></a>    qc <span class="op">=</span> QuantumCircuit(n_bits <span class="op">+</span> <span class="dv">1</span>, n_bits)</span>
<span id="cb28-14"><a href="#cb28-14" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb28-15"><a href="#cb28-15" aria-hidden="true" tabindex="-1"></a>    <span class="co"># PASSO 1: Preparação</span></span>
<span id="cb28-16"><a href="#cb28-16" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> i <span class="kw">in</span> <span class="bu">range</span>(n_bits):</span>
<span id="cb28-17"><a href="#cb28-17" aria-hidden="true" tabindex="-1"></a>        qc.h(i)</span>
<span id="cb28-18"><a href="#cb28-18" aria-hidden="true" tabindex="-1"></a>    qc.x(n_bits)</span>
<span id="cb28-19"><a href="#cb28-19" aria-hidden="true" tabindex="-1"></a>    qc.h(n_bits)</span>
<span id="cb28-20"><a href="#cb28-20" aria-hidden="true" tabindex="-1"></a>    qc.barrier()</span>
<span id="cb28-21"><a href="#cb28-21" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb28-22"><a href="#cb28-22" aria-hidden="true" tabindex="-1"></a>    <span class="co"># PASSO 2: Aplicar oráculo</span></span>
<span id="cb28-23"><a href="#cb28-23" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> tipo_funcao <span class="op">==</span> <span class="st">"constante"</span>:</span>
<span id="cb28-24"><a href="#cb28-24" aria-hidden="true" tabindex="-1"></a>        valor_constante <span class="op">=</span> random.choice([<span class="dv">0</span>, <span class="dv">1</span>])</span>
<span id="cb28-25"><a href="#cb28-25" aria-hidden="true" tabindex="-1"></a>        oraculo <span class="op">=</span> oraculo_constante(n_bits)</span>
<span id="cb28-26"><a href="#cb28-26" aria-hidden="true" tabindex="-1"></a>        <span class="cf">if</span> valor_constante <span class="op">==</span> <span class="dv">1</span>:</span>
<span id="cb28-27"><a href="#cb28-27" aria-hidden="true" tabindex="-1"></a>            oraculo.x(n_bits)</span>
<span id="cb28-28"><a href="#cb28-28" aria-hidden="true" tabindex="-1"></a>        tipo_real <span class="op">=</span> <span class="st">"CONSTANTE"</span></span>
<span id="cb28-29"><a href="#cb28-29" aria-hidden="true" tabindex="-1"></a>        tabela_classica <span class="op">=</span> [valor_constante] <span class="op">*</span> (<span class="dv">2</span><span class="op">**</span>n_bits)</span>
<span id="cb28-30"><a href="#cb28-30" aria-hidden="true" tabindex="-1"></a>    <span class="cf">else</span>:</span>
<span id="cb28-31"><a href="#cb28-31" aria-hidden="true" tabindex="-1"></a>        oraculo <span class="op">=</span> oraculo_balanceado(n_bits)</span>
<span id="cb28-32"><a href="#cb28-32" aria-hidden="true" tabindex="-1"></a>        tipo_real <span class="op">=</span> <span class="st">"BALANCEADA"</span></span>
<span id="cb28-33"><a href="#cb28-33" aria-hidden="true" tabindex="-1"></a>        metade <span class="op">=</span> <span class="dv">2</span><span class="op">**</span>(n_bits<span class="op">-</span><span class="dv">1</span>)</span>
<span id="cb28-34"><a href="#cb28-34" aria-hidden="true" tabindex="-1"></a>        tabela_classica <span class="op">=</span> [<span class="dv">0</span>]<span class="op">*</span>metade <span class="op">+</span> [<span class="dv">1</span>]<span class="op">*</span>metade</span>
<span id="cb28-35"><a href="#cb28-35" aria-hidden="true" tabindex="-1"></a>        random.shuffle(tabela_classica)</span>
<span id="cb28-36"><a href="#cb28-36" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb28-37"><a href="#cb28-37" aria-hidden="true" tabindex="-1"></a>    qc <span class="op">=</span> qc.compose(oraculo)</span>
<span id="cb28-38"><a href="#cb28-38" aria-hidden="true" tabindex="-1"></a>    qc.barrier()</span>
<span id="cb28-39"><a href="#cb28-39" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb28-40"><a href="#cb28-40" aria-hidden="true" tabindex="-1"></a>    <span class="co"># PASSO 3: Interferência</span></span>
<span id="cb28-41"><a href="#cb28-41" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> i <span class="kw">in</span> <span class="bu">range</span>(n_bits):</span>
<span id="cb28-42"><a href="#cb28-42" aria-hidden="true" tabindex="-1"></a>        qc.h(i)</span>
<span id="cb28-43"><a href="#cb28-43" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb28-44"><a href="#cb28-44" aria-hidden="true" tabindex="-1"></a>    <span class="co"># PASSO 4: Medição</span></span>
<span id="cb28-45"><a href="#cb28-45" aria-hidden="true" tabindex="-1"></a>    qc.measure(<span class="bu">range</span>(n_bits), <span class="bu">range</span>(n_bits))</span>
<span id="cb28-46"><a href="#cb28-46" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb28-47"><a href="#cb28-47" aria-hidden="true" tabindex="-1"></a>    <span class="co"># PASSO 5: Executar</span></span>
<span id="cb28-48"><a href="#cb28-48" aria-hidden="true" tabindex="-1"></a>    simulador <span class="op">=</span> AerSimulator()</span>
<span id="cb28-49"><a href="#cb28-49" aria-hidden="true" tabindex="-1"></a>    job <span class="op">=</span> simulador.run(transpile(qc, simulador), shots<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb28-50"><a href="#cb28-50" aria-hidden="true" tabindex="-1"></a>    resultado <span class="op">=</span> job.result().get_counts()</span>
<span id="cb28-51"><a href="#cb28-51" aria-hidden="true" tabindex="-1"></a>    medicao <span class="op">=</span> <span class="bu">list</span>(resultado.keys())[<span class="dv">0</span>]</span>
<span id="cb28-52"><a href="#cb28-52" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb28-53"><a href="#cb28-53" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Interpretar</span></span>
<span id="cb28-54"><a href="#cb28-54" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> medicao <span class="op">==</span> <span class="st">'0'</span> <span class="op">*</span> n_bits:</span>
<span id="cb28-55"><a href="#cb28-55" aria-hidden="true" tabindex="-1"></a>        resultado_quantum <span class="op">=</span> <span class="st">"CONSTANTE"</span></span>
<span id="cb28-56"><a href="#cb28-56" aria-hidden="true" tabindex="-1"></a>    <span class="cf">else</span>:</span>
<span id="cb28-57"><a href="#cb28-57" aria-hidden="true" tabindex="-1"></a>        resultado_quantum <span class="op">=</span> <span class="st">"BALANCEADA"</span></span>
<span id="cb28-58"><a href="#cb28-58" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb28-59"><a href="#cb28-59" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Exibir resultados</span></span>
<span id="cb28-60"><a href="#cb28-60" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="st">"="</span><span class="op">*</span><span class="dv">70</span>)</span>
<span id="cb28-61"><a href="#cb28-61" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"🧪 TESTE COM FUNÇÃO </span><span class="sc">{</span>tipo_real<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb28-62"><a href="#cb28-62" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="st">"="</span><span class="op">*</span><span class="dv">70</span>)</span>
<span id="cb28-63"><a href="#cb28-63" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"📋 Tabela clássica (primeiros 8 valores): </span><span class="sc">{</span>tabela_classica[:<span class="dv">8</span>]<span class="sc">}</span><span class="ss">..."</span>)</span>
<span id="cb28-64"><a href="#cb28-64" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"⚛️  Medição quântica: </span><span class="sc">{</span>medicao<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb28-65"><a href="#cb28-65" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"🎯 Resultado do algoritmo: </span><span class="sc">{</span>resultado_quantum<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb28-66"><a href="#cb28-66" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb28-67"><a href="#cb28-67" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> resultado_quantum <span class="op">==</span> tipo_real:</span>
<span id="cb28-68"><a href="#cb28-68" aria-hidden="true" tabindex="-1"></a>        <span class="bu">print</span>(<span class="st">"✅ CORRETO! O algoritmo identificou o tipo corretamente!"</span>)</span>
<span id="cb28-69"><a href="#cb28-69" aria-hidden="true" tabindex="-1"></a>    <span class="cf">else</span>:</span>
<span id="cb28-70"><a href="#cb28-70" aria-hidden="true" tabindex="-1"></a>        <span class="bu">print</span>(<span class="st">"❌ ERRO! Algo deu errado..."</span>)</span>
<span id="cb28-71"><a href="#cb28-71" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb28-72"><a href="#cb28-72" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"</span><span class="ch">\n</span><span class="ss">💡 Consultas necessárias:"</span>)</span>
<span id="cb28-73"><a href="#cb28-73" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"   • Clássico: até </span><span class="sc">{</span>(<span class="dv">2</span><span class="op">**</span>(n_bits<span class="op">-</span><span class="dv">1</span>)) <span class="op">+</span> <span class="dv">1</span><span class="sc">}</span><span class="ss"> consultas"</span>)</span>
<span id="cb28-74"><a href="#cb28-74" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"   • Quântico: 1 consulta"</span>)</span>
<span id="cb28-75"><a href="#cb28-75" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="st">"="</span><span class="op">*</span><span class="dv">70</span>)</span>
<span id="cb28-76"><a href="#cb28-76" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb28-77"><a href="#cb28-77" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> qc</span>
<span id="cb28-78"><a href="#cb28-78" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-79"><a href="#cb28-79" aria-hidden="true" tabindex="-1"></a><span class="co"># ============================================</span></span>
<span id="cb28-80"><a href="#cb28-80" aria-hidden="true" tabindex="-1"></a><span class="co"># TESTAR AMBOS OS CASOS</span></span>
<span id="cb28-81"><a href="#cb28-81" aria-hidden="true" tabindex="-1"></a><span class="co"># ============================================</span></span>
<span id="cb28-82"><a href="#cb28-82" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-83"><a href="#cb28-83" aria-hidden="true" tabindex="-1"></a>n <span class="op">=</span> <span class="dv">3</span>  <span class="co"># Experimente com 5, 10 ou até 15 bits!</span></span>
<span id="cb28-84"><a href="#cb28-84" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-85"><a href="#cb28-85" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"</span><span class="ch">\n</span><span class="st">🔬 EXPERIMENTO 1: Função Constante</span><span class="ch">\n</span><span class="st">"</span>)</span>
<span id="cb28-86"><a href="#cb28-86" aria-hidden="true" tabindex="-1"></a>circ1 <span class="op">=</span> executar_deutsch_jozsa(n, <span class="st">"constante"</span>)</span>
<span id="cb28-87"><a href="#cb28-87" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-88"><a href="#cb28-88" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"</span><span class="ch">\n</span><span class="st">🔬 EXPERIMENTO 2: Função Balanceada</span><span class="ch">\n</span><span class="st">"</span>)</span>
<span id="cb28-89"><a href="#cb28-89" aria-hidden="true" tabindex="-1"></a>circ2 <span class="op">=</span> executar_deutsch_jozsa(n, <span class="st">"balanceada"</span>)</span>
<span id="cb28-90"><a href="#cb28-90" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-91"><a href="#cb28-91" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"</span><span class="ch">\n</span><span class="st">📊 CONCLUSÃO:"</span>)</span>
<span id="cb28-92"><a href="#cb28-92" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"   Com </span><span class="sc">{</span>n<span class="sc">}</span><span class="ss"> bits de entrada, o computador quântico resolve o problema"</span>)</span>
<span id="cb28-93"><a href="#cb28-93" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"   com apenas 1 consulta, enquanto o clássico precisaria de até"</span>)</span>
<span id="cb28-94"><a href="#cb28-94" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"   </span><span class="sc">{</span>(<span class="dv">2</span><span class="op">**</span>(n<span class="op">-</span><span class="dv">1</span>)) <span class="op">+</span> <span class="dv">1</span><span class="sc">}</span><span class="ss"> consultas no pior caso!"</span>)</span>
<span id="cb28-95"><a href="#cb28-95" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"   Isso é uma vantagem de </span><span class="sc">{</span>(<span class="dv">2</span><span class="op">**</span>(n<span class="op">-</span><span class="dv">1</span>)) <span class="op">+</span> <span class="dv">1</span><span class="sc">}</span><span class="ss">x! 🚀"</span>)</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<pre><code>
🔬 EXPERIMENTO 1: Função Constante

======================================================================
🧪 TESTE COM FUNÇÃO CONSTANTE
======================================================================
📋 Tabela clássica (primeiros 8 valores): [0, 0, 0, 0, 0, 0, 0, 0]...
⚛️  Medição quântica: 000
🎯 Resultado do algoritmo: CONSTANTE
✅ CORRETO! O algoritmo identificou o tipo corretamente!

💡 Consultas necessárias:
   • Clássico: até 5 consultas
   • Quântico: 1 consulta
======================================================================

🔬 EXPERIMENTO 2: Função Balanceada

======================================================================
🧪 TESTE COM FUNÇÃO BALANCEADA
======================================================================
📋 Tabela clássica (primeiros 8 valores): [0, 1, 0, 0, 1, 1, 1, 0]...
⚛️  Medição quântica: 111
🎯 Resultado do algoritmo: BALANCEADA
✅ CORRETO! O algoritmo identificou o tipo corretamente!

💡 Consultas necessárias:
   • Clássico: até 5 consultas
   • Quântico: 1 consulta
======================================================================

📊 CONCLUSÃO:
   Com 3 bits de entrada, o computador quântico resolve o problema
   com apenas 1 consulta, enquanto o clássico precisaria de até
   5 consultas no pior caso!
   Isso é uma vantagem de 5x! 🚀
</code></pre>
<section id="visualização-circuito-completo-deutsch-jozsa" class="level4">
<h4 class="anchored" data-anchor-id="visualização-circuito-completo-deutsch-jozsa">Visualização: Circuito Completo Deutsch-Jozsa</h4>
<pre class="{python} {pyodide-python}"><code>
# Desenhar o circuito completo
print("Circuito quântico do Algoritmo de Deutsch-Jozsa:")
display(circ2.draw('mpl'))</code></pre>
<pre><code>Circuito quântico do Algoritmo de Deutsch-Jozsa:
</code></pre>
</section>
<section id="comparação-clássico-vs-quântico" class="level3">
<h3 class="anchored" data-anchor-id="comparação-clássico-vs-quântico">📊 Comparação: Clássico vs Quântico</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 23%">
<col style="width: 37%">
<col style="width: 38%">
</colgroup>
<thead>
<tr class="header">
<th>Característica</th>
<th>Versão Clássica (acima)</th>
<th>Versão Quântica (abaixo)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Consultas necessárias</strong></td>
<td>Até <span class="math inline">\(2^{n-1} + 1\)</span> (5 para n=3)</td>
<td><strong>1 única consulta</strong></td>
</tr>
<tr class="even">
<td><strong>Para n=3 bits</strong></td>
<td>Até 5 verificações</td>
<td>1 verificação</td>
</tr>
<tr class="odd">
<td><strong>Para n=20 bits</strong></td>
<td>Até 524,289 verificações</td>
<td>1 verificação</td>
</tr>
<tr class="even">
<td><strong>Complexidade</strong></td>
<td><span class="math inline">\(O(2^n)\)</span> exponencial</td>
<td><span class="math inline">\(O(1)\)</span> constante!</td>
</tr>
<tr class="odd">
<td><strong>Certeza do resultado</strong></td>
<td>100% após pior caso</td>
<td>100% com 1 consulta</td>
</tr>
</tbody>
</table>
</section>
<section id="estratégia-pedagógica" class="level3">
<h3 class="anchored" data-anchor-id="estratégia-pedagógica">🎯 Estratégia Pedagógica</h3>
<p>Vamos construir o algoritmo <strong>passo a passo</strong>, executando e visualizando cada etapa. Isso ajuda a entender:</p>
<ol type="1">
<li>Como a superposição permite testar todas as entradas simultaneamente</li>
<li>Como o phase kickback codifica a informação nas fases</li>
<li>Como a interferência extrai a resposta final</li>
</ol>
<p>Vamos começar!</p>
<hr>
<section id="o-circuito-detalhado-deutsch-jozsa-em-python" class="level4">
<h4 class="anchored" data-anchor-id="o-circuito-detalhado-deutsch-jozsa-em-python">O circuito detalhado Deutsch-Jozsa em Python</h4>
<p>Primeiro, importamos as bibliotecas necessárias:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb32"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="co"># ============================================</span></span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a><span class="co"># DEFINIÇÃO DOS ORÁCULOS</span></span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a><span class="co"># ============================================</span></span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-5"><a href="#cb32-5" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> oraculo_balanceado(n_qubits):</span>
<span id="cb32-6"><a href="#cb32-6" aria-hidden="true" tabindex="-1"></a>    <span class="co">"""</span></span>
<span id="cb32-7"><a href="#cb32-7" aria-hidden="true" tabindex="-1"></a><span class="co">    Cria um circuito que representa uma função BALANCEADA.</span></span>
<span id="cb32-8"><a href="#cb32-8" aria-hidden="true" tabindex="-1"></a><span class="co">    </span></span>
<span id="cb32-9"><a href="#cb32-9" aria-hidden="true" tabindex="-1"></a><span class="co">    Esta função retorna 0 para metade das entradas e 1 para a outra metade.</span></span>
<span id="cb32-10"><a href="#cb32-10" aria-hidden="true" tabindex="-1"></a><span class="co">    Implementação: CNOTs de todos os qubits de entrada para o qubit de saída.</span></span>
<span id="cb32-11"><a href="#cb32-11" aria-hidden="true" tabindex="-1"></a><span class="co">    </span></span>
<span id="cb32-12"><a href="#cb32-12" aria-hidden="true" tabindex="-1"></a><span class="co">    Equivalente quântico de: tabela_oculta = [0]*metade + [1]*metade (embaralhado)</span></span>
<span id="cb32-13"><a href="#cb32-13" aria-hidden="true" tabindex="-1"></a><span class="co">    """</span></span>
<span id="cb32-14"><a href="#cb32-14" aria-hidden="true" tabindex="-1"></a>    qc <span class="op">=</span> QuantumCircuit(n_qubits <span class="op">+</span> <span class="dv">1</span>)</span>
<span id="cb32-15"><a href="#cb32-15" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> qubit <span class="kw">in</span> <span class="bu">range</span>(n_qubits):</span>
<span id="cb32-16"><a href="#cb32-16" aria-hidden="true" tabindex="-1"></a>        qc.cx(qubit, n_qubits) <span class="co"># CNOT de todos inputs para o alvo</span></span>
<span id="cb32-17"><a href="#cb32-17" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> qc</span>
<span id="cb32-18"><a href="#cb32-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-19"><a href="#cb32-19" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> oraculo_constante(n_qubits):</span>
<span id="cb32-20"><a href="#cb32-20" aria-hidden="true" tabindex="-1"></a>    <span class="co">"""</span></span>
<span id="cb32-21"><a href="#cb32-21" aria-hidden="true" tabindex="-1"></a><span class="co">    Cria um circuito que representa uma função CONSTANTE.</span></span>
<span id="cb32-22"><a href="#cb32-22" aria-hidden="true" tabindex="-1"></a><span class="co">    </span></span>
<span id="cb32-23"><a href="#cb32-23" aria-hidden="true" tabindex="-1"></a><span class="co">    Esta função retorna sempre 0 ou sempre 1 (independente da entrada).</span></span>
<span id="cb32-24"><a href="#cb32-24" aria-hidden="true" tabindex="-1"></a><span class="co">    </span></span>
<span id="cb32-25"><a href="#cb32-25" aria-hidden="true" tabindex="-1"></a><span class="co">    Implementação:</span></span>
<span id="cb32-26"><a href="#cb32-26" aria-hidden="true" tabindex="-1"></a><span class="co">    - Retorna sempre 0: não faz nada (circuito identidade)</span></span>
<span id="cb32-27"><a href="#cb32-27" aria-hidden="true" tabindex="-1"></a><span class="co">    - Retorna sempre 1: aplica X no qubit de saída</span></span>
<span id="cb32-28"><a href="#cb32-28" aria-hidden="true" tabindex="-1"></a><span class="co">    </span></span>
<span id="cb32-29"><a href="#cb32-29" aria-hidden="true" tabindex="-1"></a><span class="co">    Equivalente quântico de: tabela_oculta = [0] * total_inputs</span></span>
<span id="cb32-30"><a href="#cb32-30" aria-hidden="true" tabindex="-1"></a><span class="co">                          ou: tabela_oculta = [1] * total_inputs</span></span>
<span id="cb32-31"><a href="#cb32-31" aria-hidden="true" tabindex="-1"></a><span class="co">    """</span></span>
<span id="cb32-32"><a href="#cb32-32" aria-hidden="true" tabindex="-1"></a>    qc <span class="op">=</span> QuantumCircuit(n_qubits <span class="op">+</span> <span class="dv">1</span>)</span>
<span id="cb32-33"><a href="#cb32-33" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Não adicionamos portas, então a saída é constante 0</span></span>
<span id="cb32-34"><a href="#cb32-34" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Para constante 1, descomente a linha abaixo:</span></span>
<span id="cb32-35"><a href="#cb32-35" aria-hidden="true" tabindex="-1"></a>    <span class="co"># qc.x(n_qubits)</span></span>
<span id="cb32-36"><a href="#cb32-36" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> qc</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb33"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="co"># ============================================</span></span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a><span class="co"># CONSTRUÇÃO DO ALGORITMO PASSO A PASSO</span></span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a><span class="co"># ============================================</span></span>
<span id="cb33-4"><a href="#cb33-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-5"><a href="#cb33-5" aria-hidden="true" tabindex="-1"></a>n <span class="op">=</span> <span class="dv">3</span>  <span class="co"># Número de bits de entrada</span></span>
<span id="cb33-6"><a href="#cb33-6" aria-hidden="true" tabindex="-1"></a>qc <span class="op">=</span> QuantumCircuit(n <span class="op">+</span> <span class="dv">1</span>, n)</span>
<span id="cb33-7"><a href="#cb33-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-8"><a href="#cb33-8" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"="</span><span class="op">*</span><span class="dv">70</span>)</span>
<span id="cb33-9"><a href="#cb33-9" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"🎯 ALGORITMO DE DEUTSCH-JOZSA - CONSTRUÇÃO PASSO A PASSO"</span>)</span>
<span id="cb33-10"><a href="#cb33-10" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"="</span><span class="op">*</span><span class="dv">70</span>)</span>
<span id="cb33-11"><a href="#cb33-11" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Testando com </span><span class="sc">{</span>n<span class="sc">}</span><span class="ss"> qubits de entrada"</span>)</span>
<span id="cb33-12"><a href="#cb33-12" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"="</span><span class="op">*</span><span class="dv">70</span>)</span>
<span id="cb33-13"><a href="#cb33-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-14"><a href="#cb33-14" aria-hidden="true" tabindex="-1"></a><span class="co"># ─────────────────────────────────────────────</span></span>
<span id="cb33-15"><a href="#cb33-15" aria-hidden="true" tabindex="-1"></a><span class="co"># PASSO 1: Inicialização</span></span>
<span id="cb33-16"><a href="#cb33-16" aria-hidden="true" tabindex="-1"></a><span class="co"># ─────────────────────────────────────────────</span></span>
<span id="cb33-17"><a href="#cb33-17" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"</span><span class="ch">\n</span><span class="st">📍 PASSO 1: Inicialização"</span>)</span>
<span id="cb33-18"><a href="#cb33-18" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"   Colocando qubits de entrada em superposição |+⟩"</span>)</span>
<span id="cb33-19"><a href="#cb33-19" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"   Preparando qubit auxiliar no estado |−⟩ para phase kickback"</span>)</span>
<span id="cb33-20"><a href="#cb33-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-21"><a href="#cb33-21" aria-hidden="true" tabindex="-1"></a><span class="co"># Inputs (0 a n-1) em Superposição |+&gt;</span></span>
<span id="cb33-22"><a href="#cb33-22" aria-hidden="true" tabindex="-1"></a>qc.h(<span class="bu">range</span>(n))</span>
<span id="cb33-23"><a href="#cb33-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-24"><a href="#cb33-24" aria-hidden="true" tabindex="-1"></a><span class="co"># Alvo (último qubit) no estado |-&gt; para gerar o KICKBACK</span></span>
<span id="cb33-25"><a href="#cb33-25" aria-hidden="true" tabindex="-1"></a>qc.x(n)</span>
<span id="cb33-26"><a href="#cb33-26" aria-hidden="true" tabindex="-1"></a>qc.h(n)</span>
<span id="cb33-27"><a href="#cb33-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-28"><a href="#cb33-28" aria-hidden="true" tabindex="-1"></a>qc.barrier()</span>
<span id="cb33-29"><a href="#cb33-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-30"><a href="#cb33-30" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"   ✅ Preparação concluída!"</span>)</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<pre><code>======================================================================
🎯 ALGORITMO DE DEUTSCH-JOZSA - CONSTRUÇÃO PASSO A PASSO
======================================================================
Testando com 3 qubits de entrada
======================================================================

📍 PASSO 1: Inicialização
   Colocando qubits de entrada em superposição |+⟩
   Preparando qubit auxiliar no estado |−⟩ para phase kickback
   ✅ Preparação concluída!
</code></pre>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb35"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Visualizar estado inicial</span></span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>estado_inicial_dj <span class="op">=</span> Statevector(qc)</span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Estado inicial - Superposição uniforme de todos os 8 estados:"</span>)</span>
<span id="cb35-4"><a href="#cb35-4" aria-hidden="true" tabindex="-1"></a>display(plot_state_qsphere(estado_inicial_dj))</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<pre><code>Estado inicial - Superposição uniforme de todos os 8 estados:
</code></pre>
</section>
<section id="demonstração-matemática-estado-inicial-do-algoritmo" class="level4">
<h4 class="anchored" data-anchor-id="demonstração-matemática-estado-inicial-do-algoritmo">Demonstração Matemática: Estado Inicial do Algoritmo</h4>
<p>Estado inicial com <span class="math inline">\(n=3\)</span> qubits de entrada e 1 qubit auxiliar:</p>
<p><span class="math display">\[|\psi_0\rangle = |000\rangle \otimes |1\rangle\]</span></p>
<p>Aplicando H em todos os 4 qubits:</p>
<p><span class="math display">\[|\psi_1\rangle = H^{\otimes 3}|000\rangle \otimes H|1\rangle\]</span></p>
<p><span class="math display">\[= \left(\frac{1}{\sqrt{2^3}} \sum_{x=0}^{7} |x\rangle\right) \otimes |-\rangle\]</span></p>
<p><span class="math display">\[= \frac{1}{2\sqrt{2}} (|000\rangle + |001\rangle + |010\rangle + ... + |111\rangle) \otimes \frac{|0\rangle - |1\rangle}{\sqrt{2}}\]</span></p>
<p>Cada um dos 8 estados possíveis tem amplitude <span class="math inline">\(\frac{1}{2\sqrt{2}}\)</span>, criando uma <strong>superposição uniforme</strong>.</p>
<pre class="{python} {pyodide-python}"><code>
# ─────────────────────────────────────────────
# PASSO 2: Aplicação do Oráculo
# ─────────────────────────────────────────────
print("\n📍 PASSO 2: Aplicação do Oráculo")
print("   Vamos usar um oráculo BALANCEADO")
print("   Aqui acontece a 'mágica': testamos TODAS as entradas simultaneamente!")

# Vamos usar o balanceado. O algoritmo deve descobrir isso.
oraculo = oraculo_balanceado(n)
# Adicionamos o oráculo ao nosso circuito principal
qc = qc.compose(oraculo)

qc.barrier()

print("   ✅ Oráculo aplicado! Informação codificada nas fases.")
</code></pre>
<pre><code>
📍 PASSO 2: Aplicação do Oráculo
   Vamos usar um oráculo BALANCEADO
   Aqui acontece a 'mágica': testamos TODAS as entradas simultaneamente!
   ✅ Oráculo aplicado! Informação codificada nas fases.
</code></pre>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb39"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Visualizar estado após oráculo</span></span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a>estado_apos_oraculo_dj <span class="op">=</span> Statevector(qc)</span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Estado após oráculo - Note as mudanças de fase:"</span>)</span>
<span id="cb39-4"><a href="#cb39-4" aria-hidden="true" tabindex="-1"></a>display(plot_state_qsphere(estado_apos_oraculo_dj))</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<pre><code>Estado após oráculo - Note as mudanças de fase:
</code></pre>
</section>
<section id="demonstração-matemática-ação-do-oráculo-balanceado" class="level4">
<h4 class="anchored" data-anchor-id="demonstração-matemática-ação-do-oráculo-balanceado">Demonstração Matemática: Ação do Oráculo Balanceado</h4>
<p>O oráculo balanceado implementa CNOTs de cada qubit de entrada para o qubit auxiliar:</p>
<p><span class="math display">\[U_f = \text{CNOT}_{0 \to 3} \cdot \text{CNOT}_{1 \to 3} \cdot \text{CNOT}_{2 \to 3}\]</span></p>
<p>Para cada estado base <span class="math inline">\(|x\rangle = |x_2x_1x_0\rangle\)</span>, o oráculo calcula:</p>
<p><span class="math display">\[f(x) = x_0 \oplus x_1 \oplus x_2\]</span></p>
<p>Esta é uma função <strong>balanceada</strong> porque:</p>
<ul>
<li><span class="math inline">\(f(000) = 0\)</span>, <span class="math inline">\(f(001) = 1\)</span>, <span class="math inline">\(f(010) = 1\)</span>, <span class="math inline">\(f(011) = 0\)</span></li>
<li><span class="math inline">\(f(100) = 1\)</span>, <span class="math inline">\(f(101) = 0\)</span>, <span class="math inline">\(f(110) = 0\)</span>, <span class="math inline">\(f(111) = 1\)</span></li>
</ul>
<p>Exatamente 4 valores retornam 0 e 4 retornam 1 (balanceado).</p>
<p>Aplicando ao estado com qubit auxiliar em <span class="math inline">\(|-\rangle\)</span>:</p>
<p><span class="math display">\[|\psi_2\rangle = \frac{1}{2\sqrt{2}} \sum_{x=0}^{7} (-1)^{f(x)} |x\rangle \otimes |-\rangle\]</span></p>
<p>Os estados agora têm <strong>fases diferentes</strong> baseadas em <span class="math inline">\(f(x)\)</span>!</p>
<pre class="{python} {pyodide-python}"><code>
# ─────────────────────────────────────────────
# PASSO 3: Interferência Final
# ─────────────────────────────────────────────
print("\n📍 PASSO 3: Interferência")
print("   Aplicando Hadamard novamente para converter FASE em AMPLITUDE")

# Aplicamos H em todos os inputs novamente.
# Isso transforma o padrão de fase (criado pelo kickback) em resposta binária.
qc.h(range(n))

print("   ✅ Interferência concluída! Pronto para medir.")
</code></pre>
<pre><code>
📍 PASSO 3: Interferência
   Aplicando Hadamard novamente para converter FASE em AMPLITUDE
   ✅ Interferência concluída! Pronto para medir.
</code></pre>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb43"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Visualizar estado antes da medição</span></span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a>estado_antes_medicao <span class="op">=</span> Statevector(qc)</span>
<span id="cb43-3"><a href="#cb43-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Estado antes da medição - Após interferência:"</span>)</span>
<span id="cb43-4"><a href="#cb43-4" aria-hidden="true" tabindex="-1"></a>display(plot_state_qsphere(estado_antes_medicao))</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<pre><code>Estado antes da medição - Após interferência:
</code></pre>
</section>
<section id="demonstração-matemática-interferência-e-resultado-final" class="level4">
<h4 class="anchored" data-anchor-id="demonstração-matemática-interferência-e-resultado-final">Demonstração Matemática: Interferência e Resultado Final</h4>
<p>Aplicando H nos 3 qubits de entrada:</p>
<p><span class="math display">\[|\psi_3\rangle = \frac{1}{8} \sum_{x=0}^{7} \sum_{z=0}^{7} (-1)^{f(x) + x \cdot z} |z\rangle\]</span></p>
<p>Para <span class="math inline">\(z = 000\)</span>:</p>
<p><span class="math display">\[\text{amplitude}(|000\rangle) = \frac{1}{8} \sum_{x=0}^{7} (-1)^{f(x)}\]</span></p>
<p>Como <span class="math inline">\(f\)</span> é balanceada (4 valores 0, 4 valores 1):</p>
<p><span class="math display">\[= \frac{1}{8}[4 \times (+1) + 4 \times (-1)] = \frac{1}{8}[4 - 4] = 0\]</span></p>
<p><strong>Interferência destrutiva completa em <span class="math inline">\(|000\rangle\)</span>!</strong></p>
<p>Para <span class="math inline">\(z = 111\)</span>:</p>
<p><span class="math display">\[\text{amplitude}(|111\rangle) = \frac{1}{8} \sum_{x=0}^{7} (-1)^{f(x) + x \cdot 111}\]</span></p>
<p>Pode-se mostrar que esta amplitude é <strong>não-zero</strong> para funções balanceadas.</p>
<p><strong>Conclusão:</strong> Nunca medimos <span class="math inline">\(|000\rangle\)</span> → função é balanceada!</p>
<pre class="{python} {pyodide-python}"><code>
# ─────────────────────────────────────────────
# PASSO 4: Medição
# ─────────────────────────────────────────────
print("\n📍 PASSO 4: Medição")
print("   Medindo apenas os qubits de entrada (não precisamos medir o auxiliar)")

# Medimos APENAS os qubits de entrada (0 a n-1)
qc.measure(range(n), range(n))

print("   ✅ Circuito completo! Pronto para executar.")
print("="*70)
</code></pre>
<pre><code>
📍 PASSO 4: Medição
   Medindo apenas os qubits de entrada (não precisamos medir o auxiliar)
   ✅ Circuito completo! Pronto para executar.
======================================================================
</code></pre>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb47"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="co"># ─────────────────────────────────────────────</span></span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a><span class="co"># PASSO 5: Execução e Interpretação</span></span>
<span id="cb47-3"><a href="#cb47-3" aria-hidden="true" tabindex="-1"></a><span class="co"># ─────────────────────────────────────────────</span></span>
<span id="cb47-4"><a href="#cb47-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"</span><span class="ch">\n</span><span class="st">🚀 EXECUTANDO O ALGORITMO...</span><span class="ch">\n</span><span class="st">"</span>)</span>
<span id="cb47-5"><a href="#cb47-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-6"><a href="#cb47-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Executar no simulador</span></span>
<span id="cb47-7"><a href="#cb47-7" aria-hidden="true" tabindex="-1"></a>simulador <span class="op">=</span> AerSimulator()</span>
<span id="cb47-8"><a href="#cb47-8" aria-hidden="true" tabindex="-1"></a>job <span class="op">=</span> simulador.run(transpile(qc, simulador), shots<span class="op">=</span><span class="dv">1000</span>)</span>
<span id="cb47-9"><a href="#cb47-9" aria-hidden="true" tabindex="-1"></a>resultado <span class="op">=</span> job.result().get_counts()</span>
<span id="cb47-10"><a href="#cb47-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-11"><a href="#cb47-11" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"📊 Resultado da medição (1000 execuções): </span><span class="sc">{</span>resultado<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb47-12"><a href="#cb47-12" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"</span><span class="ch">\n</span><span class="st">"</span> <span class="op">+</span> <span class="st">"="</span><span class="op">*</span><span class="dv">70</span>)</span>
<span id="cb47-13"><a href="#cb47-13" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"📋 INTERPRETAÇÃO DO RESULTADO"</span>)</span>
<span id="cb47-14"><a href="#cb47-14" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"="</span><span class="op">*</span><span class="dv">70</span>)</span>
<span id="cb47-15"><a href="#cb47-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-16"><a href="#cb47-16" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> <span class="st">'000'</span> <span class="kw">in</span> resultado:</span>
<span id="cb47-17"><a href="#cb47-17" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="st">"   ❌ Medimos '000' → A função é CONSTANTE"</span>)</span>
<span id="cb47-18"><a href="#cb47-18" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="st">"   (Interferência construtiva em |000⟩)"</span>)</span>
<span id="cb47-19"><a href="#cb47-19" aria-hidden="true" tabindex="-1"></a><span class="cf">else</span>:</span>
<span id="cb47-20"><a href="#cb47-20" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="st">"   ✅ Nunca medimos '000' → A função é BALANCEADA"</span>)</span>
<span id="cb47-21"><a href="#cb47-21" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="st">"   (Interferência destrutiva em |000⟩)"</span>)</span>
<span id="cb47-22"><a href="#cb47-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-23"><a href="#cb47-23" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"</span><span class="ch">\n</span><span class="st">💡 VANTAGEM QUÂNTICA:"</span>)</span>
<span id="cb47-24"><a href="#cb47-24" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"   • Versão Clássica: até </span><span class="sc">{</span>(<span class="dv">2</span><span class="op">**</span>(n<span class="op">-</span><span class="dv">1</span>)) <span class="op">+</span> <span class="dv">1</span><span class="sc">}</span><span class="ss"> consultas necessárias"</span>)</span>
<span id="cb47-25"><a href="#cb47-25" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"   • Versão Quântica: 1 consulta (sempre!)"</span>)</span>
<span id="cb47-26"><a href="#cb47-26" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"   • Speedup: </span><span class="sc">{</span>(<span class="dv">2</span><span class="op">**</span>(n<span class="op">-</span><span class="dv">1</span>)) <span class="op">+</span> <span class="dv">1</span><span class="sc">}</span><span class="ss">x mais rápido!"</span>)</span>
<span id="cb47-27"><a href="#cb47-27" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"="</span><span class="op">*</span><span class="dv">70</span>)</span>
<span id="cb47-28"><a href="#cb47-28" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb47-29"><a href="#cb47-29" aria-hidden="true" tabindex="-1"></a><span class="co"># Visualizar histograma</span></span>
<span id="cb47-30"><a href="#cb47-30" aria-hidden="true" tabindex="-1"></a>plot_histogram(resultado)</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<pre><code>
🚀 EXECUTANDO O ALGORITMO...

📊 Resultado da medição (1000 execuções): {'111': 1000}

======================================================================
📋 INTERPRETAÇÃO DO RESULTADO
======================================================================
   ✅ Nunca medimos '000' → A função é BALANCEADA
   (Interferência destrutiva em |000⟩)

💡 VANTAGEM QUÂNTICA:
   • Versão Clássica: até 5 consultas necessárias
   • Versão Quântica: 1 consulta (sempre!)
   • Speedup: 5x mais rápido!
======================================================================
</code></pre>
<hr>
</section>
</section>
</section>
<section id="entendendo-o-resultado-em-profundidade" class="level2">
<h2 class="anchored" data-anchor-id="entendendo-o-resultado-em-profundidade">🔍 Entendendo o Resultado em Profundidade</h2>
<section id="interpretação-dos-resultados" class="level3">
<h3 class="anchored" data-anchor-id="interpretação-dos-resultados">📊 Interpretação dos Resultados</h3>
<p>Após executar o algoritmo, você viu um histograma com os resultados das medições. A interpretação é simples:</p>
<p><strong>Regra de Decisão:</strong></p>
<ul>
<li>✅ <strong>Se medir <code>000</code>:</strong> A função é <strong>CONSTANTE</strong> (sempre 0 ou sempre 1)</li>
<li>✅ <strong>Se medir qualquer outra coisa</strong> (ex: <code>111</code>, <code>101</code>, etc.): A função é <strong>BALANCEADA</strong></li>
</ul>
<p>No nosso caso, usamos <code>oraculo_balanceado(3)</code>, então <strong>nunca</strong> devemos medir <code>000</code>!</p>
</section>
<section id="por-que-isso-funciona" class="level3">
<h3 class="anchored" data-anchor-id="por-que-isso-funciona">🔬 Por Que Isso Funciona?</h3>
<p>A “mágica” está em três ingredientes trabalhando juntos:</p>
<p><strong>1. Phase Kickback</strong></p>
<ul>
<li>O qubit auxiliar em <span class="math inline">\(|-\rangle\)</span> causa kickback quando o oráculo aplica X</li>
<li>Estados onde <span class="math inline">\(f(x) = 1\)</span> ganham fase negativa: <span class="math inline">\((-1)^{f(x)}\)</span></li>
<li>A informação sobre a função fica “codificada” nas fases!</li>
</ul>
<p><strong>2. Superposição Inicial</strong></p>
<ul>
<li>Todos os <span class="math inline">\(2^n\)</span> estados possíveis são processados <strong>simultaneamente</strong></li>
<li>Uma única aplicação do oráculo “consulta” todas as entradas de uma vez</li>
<li>Paralelismo quântico em ação!</li>
</ul>
<p><strong>3. Interferência Final</strong></p>
<ul>
<li>Os Hadamards finais convertem diferenças de FASE em diferenças de AMPLITUDE</li>
<li>Para funções constantes: todas as fases são iguais → interferência construtiva em <span class="math inline">\(|000\rangle\)</span></li>
<li>Para funções balanceadas: metade tem fase +, metade tem fase − → interferência <strong>destrutiva</strong> em <span class="math inline">\(|000\rangle\)</span></li>
</ul>
</section>
<section id="demonstração-matemática-simplificada" class="level3">
<h3 class="anchored" data-anchor-id="demonstração-matemática-simplificada">🧮 Demonstração Matemática Simplificada</h3>
<p><strong>Função Constante:</strong> <span class="math inline">\(f(x) = c\)</span> para todo <span class="math inline">\(x\)</span></p>
<p><span class="math display">\[\text{Amplitude}(|000\rangle) = \frac{1}{2^n}\sum_{x=0}^{2^n-1} (-1)^c = \frac{2^n \cdot (-1)^c}{2^n} = \pm 1\]</span></p>
<p><strong>Probabilidade = 100%</strong> de medir <span class="math inline">\(|000\rangle\)</span> ✅</p>
<p><strong>Função Balanceada:</strong> Metade dos <span class="math inline">\(x\)</span> têm <span class="math inline">\(f(x)=0\)</span>, metade têm <span class="math inline">\(f(x)=1\)</span></p>
<p><span class="math display">\[\text{Amplitude}(|000\rangle) = \frac{1}{2^n}\left[\frac{2^n}{2} \cdot (+1) + \frac{2^n}{2} \cdot (-1)\right] = \frac{1}{2^n}\left[\frac{2^n}{2} - \frac{2^n}{2}\right] = 0\]</span></p>
<p><strong>Probabilidade = 0%</strong> de medir <span class="math inline">\(|000\rangle\)</span> (interferência destrutiva perfeita!) ❌</p>
</section>
<section id="comparação-final-clássico-vs-quântico" class="level3">
<h3 class="anchored" data-anchor-id="comparação-final-clássico-vs-quântico">💻 Comparação Final: Clássico vs Quântico</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 17%">
<col style="width: 41%">
<col style="width: 41%">
</colgroup>
<thead>
<tr class="header">
<th>Aspecto</th>
<th>Computador Clássico</th>
<th>Computador Quântico</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Consultas ao oráculo</strong></td>
<td>Até <span class="math inline">\(2^{n-1} + 1\)</span></td>
<td><strong>1 única consulta</strong></td>
</tr>
<tr class="even">
<td><strong>Para <span class="math inline">\(n=3\)</span> bits</strong></td>
<td>Até 5 consultas</td>
<td>1 consulta</td>
</tr>
<tr class="odd">
<td><strong>Para <span class="math inline">\(n=10\)</span> bits</strong></td>
<td>Até 513 consultas</td>
<td>1 consulta</td>
</tr>
<tr class="even">
<td><strong>Para <span class="math inline">\(n=100\)</span> bits</strong></td>
<td>Até <span class="math inline">\(~6.3 \times 10^{29}\)</span> consultas</td>
<td><strong>1 consulta</strong></td>
</tr>
<tr class="odd">
<td><strong>Escalabilidade</strong></td>
<td>Cresce exponencialmente</td>
<td><strong>Constante!</strong></td>
</tr>
</tbody>
</table>
<p><strong>Vantagem:</strong> Exponencial em termos de consultas ao oráculo! 🚀</p>
</section>
<section id="o-insight-principal" class="level3">
<h3 class="anchored" data-anchor-id="o-insight-principal">🎯 O Insight Principal</h3>
<p>O algoritmo <strong>NÃO</strong> testa todas as entradas individualmente. Em vez disso:</p>
<ol type="1">
<li>Cria superposição de <strong>todas as entradas simultaneamente</strong></li>
<li>Consulta o oráculo <strong>uma única vez</strong> nesta superposição</li>
<li>Extrai informação <strong>global</strong> (propriedade de toda a função) através de <strong>interferência</strong></li>
</ol>
<p>Isso é fundamentalmente diferente de como computadores clássicos funcionam - e é a essência da <strong>vantagem quântica</strong>!</p>
</section>
<section id="limitações-importantes" class="level3">
<h3 class="anchored" data-anchor-id="limitações-importantes">⚠️ Limitações Importantes</h3>
<ul>
<li>O algoritmo só funciona para este tipo específico de problema (constante vs.&nbsp;balanceado)</li>
<li>Não diz QUAL é o valor da função, apenas sua categoria</li>
<li>Requer um oráculo quântico (reversível)</li>
<li>É um problema “artificial” - mas demonstra princípios usados em algoritmos práticos</li>
</ul>
</section>
<section id="experimento-teste-você-mesmo" class="level3">
<h3 class="anchored" data-anchor-id="experimento-teste-você-mesmo">🔬 Experimento: Teste Você Mesmo!</h3>
<p>Experimente modificar o código acima para usar <code>oraculo_constante(3)</code> em vez de <code>oraculo_balanceado(3)</code>:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb49"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Na célula onde definimos o oráculo, mude esta linha:</span></span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a>oraculo <span class="op">=</span> oraculo_constante(n)  <span class="co"># Em vez de oraculo_balanceado(n)</span></span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<p>Você deverá ver:</p>
<ul>
<li>Resultado: <code>{'000': 1000}</code> (100% das vezes)</li>
<li>Confirmando que a função é constante!</li>
</ul>
</section>
<section id="desafio-adicional" class="level3">
<h3 class="anchored" data-anchor-id="desafio-adicional">🧪 Desafio Adicional</h3>
<p>Tente aumentar <code>n</code> para 10 ou 15 bits e compare mentalmente:</p>
<ul>
<li><strong>Clássico:</strong> Precisaria de até 513 ou 16,385 consultas</li>
<li><strong>Quântico:</strong> Sempre 1 consulta! 🚀</li>
</ul>
<hr>
<hr>
</section>
</section>
<section id="resumo-e-conceitos-aprendidos" class="level2">
<h2 class="anchored" data-anchor-id="resumo-e-conceitos-aprendidos">📚 Resumo e Conceitos Aprendidos</h2>
<p>Neste notebook, você dominou os fundamentos dos algoritmos quânticos mais poderosos! Vamos recapitular:</p>
<section id="conceitos-fundamentais" class="level3">
<h3 class="anchored" data-anchor-id="conceitos-fundamentais">🎯 Conceitos Fundamentais</h3>
<section id="phase-kickback-coice-de-fase" class="level4">
<h4 class="anchored" data-anchor-id="phase-kickback-coice-de-fase">1. <strong>Phase Kickback (Coice de Fase)</strong></h4>
<ul>
<li><strong>O que é:</strong> Fenômeno onde o qubit ALVO afeta o qubit CONTROLE através de mudanças de fase</li>
<li><strong>Como funciona:</strong> Preparando o alvo em um autoestado (como <span class="math inline">\(|-\rangle\)</span>), a operação CNOT “devolve” fase para o controle</li>
<li><strong>Analogia:</strong> Como o coice de uma arma - a ação no alvo gera reação no controle</li>
<li><strong>Importância:</strong> Mecanismo fundamental que permite algoritmos quânticos eficientes</li>
</ul>
</section>
<section id="estados-especiais" class="level4">
<h4 class="anchored" data-anchor-id="estados-especiais">2. <strong>Estados Especiais</strong></h4>
<ul>
<li><strong><span class="math inline">\(|+\rangle = H|0\rangle = \frac{|0\rangle + |1\rangle}{\sqrt{2}}\)</span></strong> - Superposição com fase positiva</li>
<li><strong><span class="math inline">\(|-\rangle = H|1\rangle = \frac{|0\rangle - |1\rangle}{\sqrt{2}}\)</span></strong> - Superposição com fase negativa</li>
<li><strong>Propriedade chave:</strong> <span class="math inline">\(X|-\rangle = -|-\rangle\)</span> (autoestado de X)</li>
</ul>
</section>
<section id="algoritmo-de-deutsch-jozsa" class="level4">
<h4 class="anchored" data-anchor-id="algoritmo-de-deutsch-jozsa">3. <strong>Algoritmo de Deutsch-Jozsa</strong></h4>
<ul>
<li><strong>Problema:</strong> Determinar se uma função é constante ou balanceada</li>
<li><strong>Solução Clássica:</strong> Até <span class="math inline">\(2^{n-1} + 1\)</span> consultas necessárias</li>
<li><strong>Solução Quântica:</strong> <strong>UMA ÚNICA CONSULTA!</strong> (vantagem exponencial)</li>
<li><strong>Resultado:</strong>
<ul>
<li>Medir <span class="math inline">\(|000...0\rangle\)</span> → função é CONSTANTE</li>
<li>Medir qualquer outro valor → função é BALANCEADA</li>
</ul></li>
</ul>
</section>
</section>
<section id="técnicas-aprendidas" class="level3">
<h3 class="anchored" data-anchor-id="técnicas-aprendidas">🔬 Técnicas Aprendidas</h3>
<ol type="1">
<li><strong>Preparação de Estados</strong>
<ul>
<li>Criar superposições uniformes com Hadamard</li>
<li>Preparar estados especiais (<span class="math inline">\(|-\rangle\)</span>) para kickback</li>
</ul></li>
<li><strong>Oráculos Quânticos</strong>
<ul>
<li>Implementar funções como operações unitárias</li>
<li>Marcar estados com fases sem destruir superposição</li>
</ul></li>
<li><strong>Interferência Quântica</strong>
<ul>
<li>Usar Hadamards finais para converter fase em amplitude</li>
<li>Causar interferência destrutiva/construtiva para extrair informação</li>
</ul></li>
<li><strong>Visualizações Avançadas</strong>
<ul>
<li>Esfera de Bloch para qubits individuais</li>
<li>Q-Sphere para sistemas multi-qubit</li>
<li>Acompanhar mudanças de fase através de cores</li>
</ul></li>
</ol>
</section>
<section id="por-que-isso-é-importante" class="level3">
<h3 class="anchored" data-anchor-id="por-que-isso-é-importante">🚀 Por Que Isso É Importante?</h3>
<p>O Phase Kickback é a “mágica” por trás de:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 26%">
<col style="width: 26%">
<col style="width: 46%">
</colgroup>
<thead>
<tr class="header">
<th>Algoritmo</th>
<th>Aplicação</th>
<th>Vantagem Quântica</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Deutsch-Jozsa</strong></td>
<td>Determinar propriedade global de função</td>
<td>Exponencial em consultas</td>
</tr>
<tr class="even">
<td><strong>Grover</strong></td>
<td>Busca em banco de dados não-ordenado</td>
<td>Quadrática em tempo</td>
</tr>
<tr class="odd">
<td><strong>Shor</strong></td>
<td>Fatoração de números inteiros</td>
<td>Exponencial em tempo</td>
</tr>
<tr class="even">
<td><strong>QPE</strong></td>
<td>Estimação de fase quântica</td>
<td>Base para química quântica</td>
</tr>
</tbody>
</table>
</section>
<section id="insights-principais" class="level3">
<h3 class="anchored" data-anchor-id="insights-principais">💡 Insights Principais</h3>
<ol type="1">
<li><strong>Fase é Informação:</strong> Mudanças de fase contêm informação que pode ser extraída via interferência</li>
<li><strong>Paralelismo Quântico:</strong> Superposição permite processar múltiplas entradas simultaneamente</li>
<li><strong>Consulta Única:</strong> Com preparação adequada, uma consulta quântica equivale a múltiplas clássicas</li>
<li><strong>Interferência = Computação:</strong> A matemática acontece na interferência de amplitudes</li>
</ol>
</section>
<section id="próximos-passos" class="level3">
<h3 class="anchored" data-anchor-id="próximos-passos">🎓 Próximos Passos</h3>
<p>Agora que você domina estes conceitos, está pronto para:</p>
<ol type="1">
<li><strong>Algoritmo de Grover</strong> - Busca em espaço não-estruturado
<ul>
<li>Usa amplitude amplification (generalização de Deutsch-Jozsa)</li>
<li>Speedup quadrático: <span class="math inline">\(O(\sqrt{N})\)</span> vs.&nbsp;<span class="math inline">\(O(N)\)</span> clássico</li>
</ul></li>
<li><strong>Algoritmo de Shor</strong> - Fatoração de inteiros
<ul>
<li>Usa Quantum Phase Estimation (QPE)</li>
<li>Ameaça à criptografia RSA moderna</li>
</ul></li>
<li><strong>VQE e QAOA</strong> - Otimização variacional
<ul>
<li>Aplicações em química quântica e otimização combinatória</li>
<li>Algoritmos híbridos quântico-clássicos</li>
</ul></li>
<li><strong>Simulação Quântica</strong> - Modelar sistemas quânticos complexos
<ul>
<li>Química computacional, ciência de materiais</li>
<li>Algoritmos de Hamiltonian simulation</li>
</ul></li>
</ol>
</section>
<section id="reflexão-final" class="level3">
<h3 class="anchored" data-anchor-id="reflexão-final">✨ Reflexão Final</h3>
<p>Você acabou de implementar um algoritmo que demonstra <strong>supremacia quântica</strong> em termos de complexidade de consulta! O Deutsch-Jozsa prova que computadores quânticos podem resolver certos problemas fundamentalmente mais rápido que computadores clássicos.</p>
<p>A jornada de aprendizado em computação quântica é como subir uma escada:</p>
<ul>
<li>✅ <strong>Superposição</strong> - você aprendeu em <a href="01-intro.ipynb">01-intro.ipynb</a></li>
<li>✅ <strong>Emaranhamento</strong> - você aprendeu em <a href="02-teletransport.ipynb">02-teletransport.ipynb</a><br>
</li>
<li>✅ <strong>Interferência</strong> - você aprendeu em <a href="04-Hadamard-experiment.ipynb">04-Hadamard-experiment.ipynb</a></li>
<li>✅ <strong>Phase Kickback</strong> - você dominou neste notebook!</li>
<li>🚀 <strong>Algoritmos Avançados</strong> - você está pronto!</li>
</ul>
<p><strong>Parabéns por chegar até aqui! Você agora entende os mecanismos que fazem a computação quântica ser poderosa.</strong> 🎉</p>
<hr>
</section>
<section id="referências-adicionais" class="level3">
<h3 class="anchored" data-anchor-id="referências-adicionais">📖 Referências Adicionais</h3>
<ul>
<li><strong>Deutsch-Jozsa Algorithm:</strong> Deutsch, D., &amp; Jozsa, R. (1992). “Rapid solution of problems by quantum computation.” <em>Proceedings of the Royal Society of London A</em>, 439(1907), 553-558.</li>
<li><strong>Nielsen &amp; Chuang:</strong> Chapter 1.4 (Deutsch-Jozsa), Chapter 6 (Quantum Algorithms)</li>
<li><strong>Qiskit Textbook:</strong> <a href="https://qiskit.org/textbook/ch-algorithms/deutsch-jozsa.html">Deutsch-Jozsa Algorithm</a></li>
</ul>
<hr>


<!-- -->

</section>
</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copiada");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copiada");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
    const viewSource = window.document.getElementById('quarto-view-source') ||
                       window.document.getElementById('quarto-code-tools-source');
    if (viewSource) {
      const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
      viewSource.addEventListener("click", function(e) {
        if (sourceUrl) {
          // rstudio viewer pane
          if (/\bcapabilities=\b/.test(window.location)) {
            window.open(sourceUrl);
          } else {
            window.location.href = sourceUrl;
          }
        } else {
          const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
          modal.show();
        }
        return false;
      });
    }
    function toggleCodeHandler(show) {
      return function(e) {
        const cellDetails = window.document.querySelectorAll(".cell details.code-fold");
        for (let i=0; i<cellDetails.length; i++) {
          const details = cellDetails[i];
          if (show) {
            details.open = true;
          } else {
            details.removeAttribute("open");
          }
        }
        const cellCodeDivs = window.document.querySelectorAll(".cell div.sourceCode.cell-code");
        const fromCls = show ? "hidden" : "unhidden";
        const toCls = show ? "unhidden" : "hidden";
        for (let i=0; i<cellCodeDivs.length; i++) {
          const codeDiv = cellCodeDivs[i];
          if (codeDiv.classList.contains(fromCls)) {
            codeDiv.classList.remove(fromCls);
            codeDiv.classList.add(toCls);
          } 
        }
        return false;
      }
    }
    const hideAllCode = window.document.getElementById("quarto-hide-all-code");
    if (hideAllCode) {
      hideAllCode.addEventListener("click", toggleCodeHandler(false));
    }
    const showAllCode = window.document.getElementById("quarto-show-all-code");
    if (showAllCode) {
      showAllCode.addEventListener("click", toggleCodeHandler(true));
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/maxwellamaral\.github\.io\/aula-quantum");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script><div class="modal fade" id="quarto-embedded-source-code-modal" tabindex="-1" aria-labelledby="quarto-embedded-source-code-modal-label" aria-hidden="true"><div class="modal-dialog modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="quarto-embedded-source-code-modal-label">Código fonte</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb50" data-shortcodes="false"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a><span class="an">title:</span><span class="co"> "Aula 07 — Interferência e Algoritmo de Deutsch-Jozsa"</span></span>
<span id="cb50-3"><a href="#cb50-3" aria-hidden="true" tabindex="-1"></a><span class="an">subtitle:</span><span class="co"> "Fundamentos de Computação Quântica — Curso de Extensão"</span></span>
<span id="cb50-4"><a href="#cb50-4" aria-hidden="true" tabindex="-1"></a><span class="an">author:</span><span class="co"> "Prof. Me. Maxwell Anderson Ielpo do Amaral"</span></span>
<span id="cb50-5"><a href="#cb50-5" aria-hidden="true" tabindex="-1"></a><span class="an">institute:</span><span class="co"> "Instituto Federal de Educação, Ciência e Tecnologia da Paraíba (IFPB) — Campus João Pessoa"</span></span>
<span id="cb50-6"><a href="#cb50-6" aria-hidden="true" tabindex="-1"></a><span class="an">date:</span><span class="co"> "2026-10-20"</span></span>
<span id="cb50-7"><a href="#cb50-7" aria-hidden="true" tabindex="-1"></a><span class="an">lang:</span><span class="co"> pt-BR</span></span>
<span id="cb50-8"><a href="#cb50-8" aria-hidden="true" tabindex="-1"></a><span class="an">format:</span></span>
<span id="cb50-9"><a href="#cb50-9" aria-hidden="true" tabindex="-1"></a><span class="co">  html:</span></span>
<span id="cb50-10"><a href="#cb50-10" aria-hidden="true" tabindex="-1"></a><span class="co">    toc: true</span></span>
<span id="cb50-11"><a href="#cb50-11" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb50-12"><a href="#cb50-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb50-13"><a href="#cb50-13" aria-hidden="true" tabindex="-1"></a>::: {.callout-tip}</span>
<span id="cb50-14"><a href="#cb50-14" aria-hidden="true" tabindex="-1"></a><span class="fu">## 📽️ Material da Aula</span></span>
<span id="cb50-15"><a href="#cb50-15" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>📄 <span class="co">[</span><span class="ot">Baixar Apostila Completa em PDF</span><span class="co">](../apostila.pdf)</span>{target="_blank"}</span>
<span id="cb50-16"><a href="#cb50-16" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>🧪 <span class="co">[</span><span class="ot">Galeria de Simuladores Interativos</span><span class="co">](/assets/simuladores/)</span>{target="_blank"}</span>
<span id="cb50-17"><a href="#cb50-17" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>🚀 <span class="co">[</span><span class="ot">Executar no Google Colab</span><span class="co">](https://colab.research.google.com/github/maxwellamaral/aula-quantum/blob/main/notebooks/05-interference.ipynb)</span>{target="_blank"}</span>
<span id="cb50-18"><a href="#cb50-18" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb50-19"><a href="#cb50-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb50-20"><a href="#cb50-20" aria-hidden="true" tabindex="-1"></a>{{&lt; include _content.qmd &gt;}}</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button" data-in-quarto-modal=""><i class="bi"></i></button></div>
</div></div></div></div></div>
</div> <!-- /content -->
<script type="module">
/**
 * Factory function to create different types of cells based on options.
 * @param {Object} cellData - JSON object containing code, id, and options.
 * @returns {BaseCell} Instance of the appropriate cell class.
 */
globalThis.qpyodideCreateCell = function(cellData) {
    switch (cellData.options.context) {
        case 'interactive':
            return new InteractiveCell(cellData);
        case 'output':
            return new OutputCell(cellData);
        case 'setup':
            return new SetupCell(cellData);
        default:
            return new InteractiveCell(cellData);
            // throw new Error('Invalid cell type specified in options.');
    }
}  

/**
 * CellContainer class for managing a collection of cells.
 * @class
 */
class CellContainer {
    /**
     * Constructor for CellContainer.
     * Initializes an empty array to store cells.
     * @constructor
     */
    constructor() {
        this.cells = [];
    }

    /**
     * Add a cell to the container.
     * @param {BaseCell} cell - Instance of a cell (BaseCell or its subclasses).
     */
    addCell(cell) {
        this.cells.push(cell);
    }

    /**
     * Execute all cells in the container.
     */
    async executeAllCells() {
        for (const cell of this.cells) {
            await cell.executeCode();
        }
    }

    /**
     * Execute all cells in the container.
     */
    async autoRunExecuteAllCells() {
        for (const cell of this.cells) {
            await cell.autoRunExecuteCode();
        }
    }
}
  

/**
 * BaseCell class for handling code execution using Pyodide.
 * @class
 */
class BaseCell {
    /**
     * Constructor for BaseCell.
     * @constructor
     * @param {Object} cellData - JSON object containing code, id, and options.
     */
    constructor(cellData) {
        this.code = cellData.code;
        this.id = cellData.id;
        this.options = cellData.options;
        this.insertionLocation = document.getElementById(`qpyodide-insertion-location-${this.id}`);
        this.executionLock = false;
    }

    cellOptions() {
        // Subclass this? 
        console.log(this.options);
        return this.options;
    }

    /**
     * Execute the Python code using Pyodide.
     * @returns {*} Result of the code execution.
     */
    async executeCode() {
        // Execute code using Pyodide
        const result = getPyodide().runPython(this.code);
        return result;
    }
};

/**
 * InteractiveCell class for creating editable code editor with Monaco Editor.
 * @class
 * @extends BaseCell
 */
class InteractiveCell extends BaseCell {

    /**
     * Constructor for InteractiveCell.
     * @constructor
     * @param {Object} cellData - JSON object containing code, id, and options.
     */
    constructor(cellData) {
        super(cellData);
        this.editor = null;
        this.setupElement();
        this.setupMonacoEditor();
    }

    /**
     * Set up the interactive cell elements
     */
    setupElement() {

        // Create main div element
        var mainDiv = document.createElement('div');
        mainDiv.id = `qpyodide-interactive-area-${this.id}`;
        mainDiv.className = `qpyodide-interactive-area`;
        if (this.options.classes) {
            mainDiv.className += " " + this.options.classes
        }

        // Add a unique cell identifier that users can customize
        if (this.options.label) {
            mainDiv.setAttribute('data-id', this.options.label);
        }

        // Create toolbar div
        var toolbarDiv = document.createElement('div');
        toolbarDiv.className = 'qpyodide-editor-toolbar';
        toolbarDiv.id = `qpyodide-editor-toolbar-${this.id}`;

        // Create a div to hold the left buttons
        var leftButtonsDiv = document.createElement('div');
        leftButtonsDiv.className = 'qpyodide-editor-toolbar-left-buttons';

        // Create a div to hold the right buttons
        var rightButtonsDiv = document.createElement('div');
        rightButtonsDiv.className = 'qpyodide-editor-toolbar-right-buttons';

        // Create Run Code button
        var runCodeButton = document.createElement('button');
        runCodeButton.className = 'btn btn-default qpyodide-button qpyodide-button-run';
        runCodeButton.disabled = true;
        runCodeButton.type = 'button';
        runCodeButton.id = `qpyodide-button-run-${this.id}`;
        runCodeButton.textContent = '🟡 Loading Pyodide...';
        runCodeButton.title = `Run code (Shift + Enter)`;

        // Append buttons to the leftButtonsDiv
        leftButtonsDiv.appendChild(runCodeButton);

        // Create Reset button
        var resetButton = document.createElement('button');
        resetButton.className = 'btn btn-light btn-xs qpyodide-button qpyodide-button-reset';
        resetButton.type = 'button';
        resetButton.id = `qpyodide-button-reset-${this.id}`;
        resetButton.title = 'Start over';
        resetButton.innerHTML = '<i class="fa-solid fa-arrows-rotate"></i>';

        // Create Copy button
        var copyButton = document.createElement('button');
        copyButton.className = 'btn btn-light btn-xs qpyodide-button qpyodide-button-copy';
        copyButton.type = 'button';
        copyButton.id = `qpyodide-button-copy-${this.id}`;
        copyButton.title = 'Copy code';
        copyButton.innerHTML = '<i class="fa-regular fa-copy"></i>';

        // Append buttons to the rightButtonsDiv
        rightButtonsDiv.appendChild(resetButton);
        rightButtonsDiv.appendChild(copyButton);

        // Create console area div
        var consoleAreaDiv = document.createElement('div');
        consoleAreaDiv.id = `qpyodide-console-area-${this.id}`;
        consoleAreaDiv.className = 'qpyodide-console-area';

        // Create editor div
        var editorDiv = document.createElement('div');
        editorDiv.id = `qpyodide-editor-${this.id}`;
        editorDiv.className = 'qpyodide-editor';

        // Create output code area div
        var outputCodeAreaDiv = document.createElement('div');
        outputCodeAreaDiv.id = `qpyodide-output-code-area-${this.id}`;
        outputCodeAreaDiv.className = 'qpyodide-output-code-area';
        outputCodeAreaDiv.setAttribute('aria-live', 'assertive');

        // Create pre element inside output code area
        var preElement = document.createElement('pre');
        preElement.style.visibility = 'hidden';
        outputCodeAreaDiv.appendChild(preElement);

        // Create output graph area div
        var outputGraphAreaDiv = document.createElement('div');
        outputGraphAreaDiv.id = `qpyodide-output-graph-area-${this.id}`;
        outputGraphAreaDiv.className = 'qpyodide-output-graph-area';

        // Append buttons to the toolbar
        toolbarDiv.appendChild(leftButtonsDiv);
        toolbarDiv.appendChild(rightButtonsDiv);

        // Append all elements to the main div
        mainDiv.appendChild(toolbarDiv);
        consoleAreaDiv.appendChild(editorDiv);
        consoleAreaDiv.appendChild(outputCodeAreaDiv);
        mainDiv.appendChild(consoleAreaDiv);
        mainDiv.appendChild(outputGraphAreaDiv);

        // Insert the dynamically generated object at the document location.
        this.insertionLocation.appendChild(mainDiv);
    }

    /**
     * Set up Monaco Editor for code editing.
     */
    setupMonacoEditor() {

        // Retrieve the previously created document elements
        this.runButton = document.getElementById(`qpyodide-button-run-${this.id}`);
        this.resetButton = document.getElementById(`qpyodide-button-reset-${this.id}`);
        this.copyButton = document.getElementById(`qpyodide-button-copy-${this.id}`);
        this.editorDiv = document.getElementById(`qpyodide-editor-${this.id}`);
        this.outputCodeDiv = document.getElementById(`qpyodide-output-code-area-${this.id}`);
        this.outputGraphDiv = document.getElementById(`qpyodide-output-graph-area-${this.id}`);
        
        // Store reference to the object
        var thiz = this;

        // Load the Monaco Editor and create an instance
        require(['vs/editor/editor.main'], function () {
            thiz.editor = monaco.editor.create(
                thiz.editorDiv, {
                    value: thiz.code,
                    language: 'python',
                    theme: 'vs-dark',
                    automaticLayout: true,           // Works wonderfully with RevealJS
                    scrollBeyondLastLine: false,
                    minimap: {
                        enabled: false
                    },
                    fontSize: '17.5pt',              // Bootstrap is 1 rem
                    renderLineHighlight: "none",     // Disable current line highlighting
                    hideCursorInOverviewRuler: true,  // Remove cursor indictor in right hand side scroll bar
                    readOnly: thiz.options['read-only'] ?? false
                }
            );
        
            // Store the official counter ID to be used in keyboard shortcuts
            thiz.editor.__qpyodideCounter = thiz.id;
        
            // Store the official div container ID
            thiz.editor.__qpyodideEditorId = `qpyodide-editor-${thiz.id}`;
        
            // Store the initial code value and options
            thiz.editor.__qpyodideinitialCode = thiz.code;
            thiz.editor.__qpyodideOptions = thiz.options;
        
            // Set at the model level the preferred end of line (EOL) character to LF.
            // This prevent `\r\n` from being given to the Pyodide engine if the user is on Windows.
            // See details in: https://github.com/coatless/quarto-Pyodide/issues/94
            // Associated error text: 
            // Error: <text>:1:7 unexpected input
        
            // Retrieve the underlying model
            const model = thiz.editor.getModel();
            // Set EOL for the model
            model.setEOL(monaco.editor.EndOfLineSequence.LF);
        
            // Dynamically modify the height of the editor window if new lines are added.
            let ignoreEvent = false;
            const updateHeight = () => {
            const contentHeight = thiz.editor.getContentHeight();
            // We're avoiding a width change
            //editorDiv.style.width = `${width}px`;
            thiz.editorDiv.style.height = `${contentHeight}px`;
                try {
                    ignoreEvent = true;
            
                    // The key to resizing is this call
                    thiz.editor.layout();
                } finally {
                    ignoreEvent = false;
                }
            };
        
            // Helper function to check if selected text is empty
            function isEmptyCodeText(selectedCodeText) {
                return (selectedCodeText === null || selectedCodeText === undefined || selectedCodeText === "");
            }
        
            // Registry of keyboard shortcuts that should be re-added to each editor window
            // when focus changes.
            const addPyodideKeyboardShortCutCommands = () => {
            // Add a keydown event listener for Shift+Enter to run all code in cell
            thiz.editor.addCommand(monaco.KeyMod.Shift | monaco.KeyCode.Enter, () => {
                // Retrieve all text inside the editor
                thiz.runCode(thiz.editor.getValue());
            });
        
            // Add a keydown event listener for CMD/Ctrl+Enter to run selected code
            thiz.editor.addCommand(monaco.KeyMod.CtrlCmd | monaco.KeyCode.Enter, () => {
                    // Get the selected text from the editor
                    const selectedText = thiz.editor.getModel().getValueInRange(thiz.editor.getSelection());
                    // Check if no code is selected
                    if (isEmptyCodeText(selectedText)) {
                        // Obtain the current cursor position
                        let currentPosition = thiz.editor.getPosition();
                        // Retrieve the current line content
                        let currentLine = thiz.editor.getModel().getLineContent(currentPosition.lineNumber);
                
                        // Propose a new position to move the cursor to
                        let newPosition = new monaco.Position(currentPosition.lineNumber + 1, 1);
                
                        // Check if the new position is beyond the last line of the editor
                        if (newPosition.lineNumber > thiz.editor.getModel().getLineCount()) {
                            // Add a new line at the end of the editor
                            thiz.editor.executeEdits("addNewLine", [{
                            range: new monaco.Range(newPosition.lineNumber, 1, newPosition.lineNumber, 1),
                            text: "\n", 
                            forceMoveMarkers: true,
                            }]);
                        }
                        
                        // Run the entire line of code.
                        thiz.runCode(currentLine);
                
                        // Move cursor to new position
                        thiz.editor.setPosition(newPosition);
                    } else {
                        // Code to run when Ctrl+Enter is pressed with selected code
                        thiz.runCode(selectedText);
                    }
                });
            }
        
            // Register an on focus event handler for when a code cell is selected to update
            // what keyboard shortcut commands should work.
            // This is a workaround to fix a regression that happened with multiple
            // editor windows since Monaco 0.32.0 
            // https://github.com/microsoft/monaco-editor/issues/2947
            thiz.editor.onDidFocusEditorText(addPyodideKeyboardShortCutCommands);
        
            // Register an on change event for when new code is added to the editor window
            thiz.editor.onDidContentSizeChange(updateHeight);
        
            // Manually re-update height to account for the content we inserted into the call
            updateHeight();
                
        });

        
        // Add a click event listener to the run button
        thiz.runButton.onclick = function () {
            thiz.runCode(
                thiz.editor.getValue()
            );
        };
        
        // Add a click event listener to the reset button
        thiz.copyButton.onclick = function () {
            // Retrieve current code data
            const data = thiz.editor.getValue();
            
            // Write code data onto the clipboard.
            navigator.clipboard.writeText(data || "");
        };
        
        // Add a click event listener to the copy button
        thiz.resetButton.onclick = function () {
            thiz.editor.setValue(thiz.editor.__qpyodideinitialCode);
        };
    }

    disableInteractiveCells() {
        // Enable locking of execution for the cell
        this.executionLock = true;

        // Disallowing execution of other code cells
        document.querySelectorAll(".qpyodide-button-run").forEach((btn) => {
            btn.disabled = true;
        });
    }

    enableInteractiveCells() {
        // Remove locking of execution for the cell
        this.executionLock = false;

        // All execution of other code cells
        document.querySelectorAll(".qpyodide-button-run").forEach((btn) => {
            btn.disabled = false;
        });
    }

    /**
     * Execute the Python code inside the editor.
     */
    async runCode(code) {
        
        // Check if we have an execution lock
        if (this.executeLock) return; 
        
        this.disableInteractiveCells();

        // Force wait procedure
        await mainPyodide;

        // Clear the output stock
        qpyodideResetOutputArray();

        // Generate a new canvas element, avoid attaching until the end
        let graphFigure = document.createElement("figure");
        document.pyodideMplTarget = graphFigure;

        console.log("Running code!");
        // Obtain results from the base class
        try {
            // Always check to see if the user adds new packages
            await mainPyodide.loadPackagesFromImports(code);

            // Process result
            const output = await mainPyodide.runPythonAsync(code);

            // Add output
            qpyodideAddToOutputArray(output, "stdout");
        } catch (err) {
            // Add error message
            qpyodideAddToOutputArray(err, "stderr");
            // TODO: There has to be a way to remove the Pyodide portion of the errors... 
        }

        const result = qpyodideRetrieveOutput();

        // Nullify the output area of content
        this.outputCodeDiv.innerHTML = "";
        this.outputGraphDiv.innerHTML = "";        

        // Design an output object for messages
        const pre = document.createElement("pre");
        if (/\S/.test(result)) {
            // Display results as HTML elements to retain output styling
            const div = document.createElement("div");
            div.innerHTML = result;
            pre.appendChild(div);
        } else {
            // If nothing is present, hide the element.
            pre.style.visibility = "hidden";
        }

        // Add output under interactive div
        this.outputCodeDiv.appendChild(pre);

        // Place the graphics onto the page
        if (graphFigure) {

            if (this.options['fig-cap']) {
                // Create figcaption element
                const figcaptionElement = document.createElement('figcaption');
                figcaptionElement.innerText = this.options['fig-cap'];
                // Append figcaption to figure
                graphFigure.appendChild(figcaptionElement);    
            }

            this.outputGraphDiv.appendChild(graphFigure);
        }

        // Re-enable execution
        this.enableInteractiveCells();
    }
};

/**
 * OutputCell class for customizing and displaying output.
 * @class
 * @extends BaseCell
 */
class OutputCell extends BaseCell {
    /**
     * Constructor for OutputCell.
     * @constructor
     * @param {Object} cellData - JSON object containing code, id, and options.
     */
    constructor(cellData) {
      super(cellData);
    }
  
    /**
     * Display customized output on the page.
     * @param {*} output - Result to be displayed.
     */
    displayOutput(output) {
        const results = this.executeCode();
        return results;
    }
  }

/**
 * SetupCell class for suppressed output.
 * @class
 * @extends BaseCell
 */
class SetupCell extends BaseCell {
    /**
     * Constructor for SetupCell.
     * @constructor
     * @param {Object} cellData - JSON object containing code, id, and options.
     */
    constructor(cellData) {
        super(cellData);
    }

    /**
     * Execute the Python code without displaying the results.
     */
    runSetupCode() {
        // Execute code without displaying output
        this.executeCode();
    }
};
</script>
<script type="module">
// Handle cell initialization initialization
qpyodideCellDetails.map(
    (entry) => {
      // Handle the creation of the element
      qpyodideCreateCell(entry);
    }
  );
</script>




</body></html>